// 실제 고객 데이터가 아닌, 화면 구조를 보여주기 위한 예시(더미) 데이터입니다.

export const text = {
  screenName: { ko: 'MMW형 CMA 투자결과 보고서', en: 'MMW-type CMA Investment Result Report' },
  greetingAfter: { ko: '님 안녕하세요.', en: '.' },
  accountNumber: { ko: '계좌번호', en: 'Account Number' },
  accountName: { ko: '계좌명', en: 'Account Name' },
  serviceStartDate: { ko: '서비스개시일', en: 'Service Start Date' },
  recommender: { ko: '투자권유자', en: 'Recommender' },
  reportPeriod: { ko: '보고기간', en: 'Report Period' },
  reportBaseDate: { ko: '보고기준일', en: 'Report Base Date' },
  resultTit: { ko: 'MMW형 CMA운용결과', en: 'MMW-type CMA Management Results' },
  col: {
    date: { ko: '일자', en: 'Date' },
    evalAmount: { ko: '평가금액', en: 'Valuation' },
    profitLoss: { ko: '투자손익', en: 'Profit/Loss' },
  },
  resultNote1: { ko: '상기 투자손익은 수수료, 세금이 반영된 금액입니다.', en: 'The above profit/loss reflects fees and taxes.' },
  resultNote2: { ko: '상기 평가금액은 해당 월, 마지막 영업일에 매수된 금액입니다.', en: 'The above valuation is the amount purchased on the last business day of the month.' },
  demandTit: { ko: '수시형 MMW수익율', en: 'On-Demand MMW Return' },
  demandSub: { ko: '(세전, 수수료 차감 전 투자수익율임)', en: '(Pre-tax, before fee deduction)' },
  demandUnit: { ko: '(수익율은 연수익율 기준임)', en: '(Return is on an annualized basis)' },
  target: { ko: '대상', en: 'Target' },
  individual: { ko: '개인', en: 'Individual' },
  corporate: { ko: '법인', en: 'Corporate' },
  note: { ko: '비고', en: 'Note' },
  investReturn: { ko: '투자수익율', en: 'Investment Return' },
  demandNote: { ko: 'Wrap수수료 개인 (연)0.1%, 법인 (연)0.05%', en: 'Wrap fee: Individual (annual) 0.1%, Corporate (annual) 0.05%' },
  termTit: { ko: '기간형 MMW수익율 안내', en: 'Term-type MMW Return Notice' },
  depositPeriod: { ko: '예치기간', en: 'Deposit Period' },
  monthUnit: { ko: '개월', en: ' Month(s)' },
  more: { ko: '더보기', en: 'More' },
  less: { ko: '접기', en: 'Collapse' },
  termNote1: { ko: 'Wrap수수료 개인/법인 (연)0.05%', en: 'Wrap fee: Individual/Corporate (annual) 0.05%' },
  termNote2: { ko: '기간형 MMW 종목의 신규 매수 중단', en: 'New purchases of term-type MMW products suspended' },
  termNote2Sub1: { ko: '중단일 2022.03.02(수) 부터', en: 'Suspended from Mar 2, 2022 (Wed)' },
  termNote2Sub2: {
    ko: '유의사항 : 기존 매수건에 대해서는 만기 자동 상환, 만기 이전 매도시 중도해지이율 적용, 향후 매수 재개시 안내예정',
    en: 'Note: Existing holdings will be automatically redeemed at maturity; an early-termination rate applies if sold before maturity; notice will be given if purchases resume.',
  },
  feeTit: { ko: '수수료 정보', en: 'Fee Information' },
  col2: {
    period: { ko: '기간', en: 'Period' },
    calcDays: { ko: '산정일수', en: 'Days Calculated' },
    feeIncurred: { ko: '발생수수료', en: 'Fee Incurred' },
  },
  operationTit: { ko: 'MMW CMA 운용방식', en: 'MMW CMA Management Method' },
  operationNotes: [
    { ko: '신용등급 AAA이상의 우량금융기관 예금 및 현금성자산에 100% 투자하여 안정적인 이자소득을 추구합니다.', en: 'Invests 100% in deposits and cash equivalents of prime financial institutions rated AAA or higher, pursuing stable interest income.' },
    { ko: '안정적인 수익추구를 목표로 운용하며 수시입출금 거래가 많은 고객에게 적합합니다.', en: 'Managed to pursue stable returns, suitable for customers with frequent deposits and withdrawals.' },
    { ko: '한국은행의 기준금리 변동과 시장상황에 따라 수익률이 변할 수 있으며, 해당 유형은 예금자 보호법의 보호를 받지 않는 상품입니다.', en: 'Returns may vary with the Bank of Korea base rate and market conditions; this product type is not protected under the Depositor Protection Act.' },
  ],
  termHistoryTit: { ko: '기간물 거래내역', en: 'Term Transaction History' },
  col3: {
    tradeDate: { ko: '거래일자', en: 'Trade Date' },
    securityName: { ko: '종목명', en: 'Security Name' },
    tradeType: { ko: '매매구분', en: 'Trade Type' },
    tradeAmount: { ko: '매매금액', en: 'Trade Amount' },
  },
  noResult: { ko: '내역이 없습니다', en: 'No records found.' },
  advisorTit: { ko: '투자권유자 및 운용역 정보', en: 'Recommender & Manager Information' },
  fpInfo: { ko: 'FP정보', en: 'FP Information' },
  contact: { ko: '연락처', en: 'Contact' },
  managerInfo: { ko: '운용역정보', en: 'Manager Information' },
  career: { ko: '경력사항', en: 'Career' },
  advisorNote: {
    ko: '고객님의 투자목적, 투자경험, 위험 선호의 정도 및 투자예정기간 등에 변경사항이 있을 경우, 담당 일임자산운용사와 상담을 통하여 투자일임방법을 변경하시기 바랍니다.',
    en: 'If there are any changes to your investment objectives, experience, risk tolerance, or intended investment period, please consult your discretionary asset manager to update your investment management method.',
  },
};

export const sampleData = {
  customerName: { ko: '류원희', en: 'Wonhee Ryu' },
  accountNo: '01234567890',
  serviceStartDate: '1990-02-11',
  recommender: { ko: '류원희', en: 'Wonhee Ryu' },
  periodFrom: '2024/03/01',
  periodTo: '2024/05/31',
  baseDate: '2024-05-31',
  results: [
    { date: '2024.03.29', evalAmount: 221455, profitLoss: 390 },
    { date: '2024.04.30', evalAmount: 221918, profitLoss: 437 },
    { date: '2024.05.31', evalAmount: 246102, profitLoss: 546 },
  ],
  individualReturn: 2.59,
  corporateReturn: 2.45,
  termReturns: [
    1.85, 1.90, 1.95, 2.00, 2.05, 2.10, 2.15, 2.20, 2.25, 2.30, 2.35, 2.40,
  ],
  fees: [
    { from: '2024.03.01', to: '2024.03.31', days: 31, fee: 5 },
    { from: '2024.04.01', to: '2024.04.30', days: 30, fee: 5 },
    { from: '2024.05.01', to: '2024.05.31', days: 31, fee: 11 },
  ],
  termTrades: [],
  fpInfo: { ko: '신한투자증권', en: 'Shinhan Investment Corp.' },
  contact: { ko: '', en: '' },
  managerInfo: { ko: '랩운용부 부장 손은주', en: 'Wrap Management Dept. Team Lead Eunju Son' },
  career: {
    ko: '1999.02 이화여자대학교 수학과\n1999.04~2020.12 신한투자증권 금융상품부, 퇴직연금부, 투자상품부\n2021.01 ~ 신한투자증권 랩운용부\n- 투자자산운용사 자격증 보유',
    en: 'Feb 1999 Ewha Womans University, Mathematics\nApr 1999 – Dec 2020 Shinhan Investment Corp. Financial Products, Retirement Pension, Investment Products Divisions\nJan 2021 – Present Shinhan Investment Corp. Wrap Management Dept.\n- Holds Investment Asset Management Professional certification',
  },
};
