// 실제 고객 데이터가 아닌, 화면 구조를 보여주기 위한 예시(더미) 데이터입니다.

export const text = {
  screenName: { ko: '펀드 수익률 보고서', en: 'Fund Return Report' },
  greetingAfter: { ko: '님 안녕하세요.', en: '.' },
  accountNumber: { ko: '계좌번호', en: 'Account Number' },
  accountName: { ko: '계좌명', en: 'Account Name' },
  balanceDate: { ko: '잔고기준일', en: 'Balance Base Date' },
  fundReturnTit: { ko: '펀드 수익률 현황', en: 'Fund Return Status' },
  totalPrefix: { ko: '총 ', en: 'Total: ' },
  totalSuffix: { ko: '건', en: ' items' },
  col: {
    seqNo: { ko: '순번', en: 'No.' },
    fundName: { ko: '펀드명', en: 'Fund Name' },
    details: { ko: '상세보기', en: 'Details' },
  },
  noResult: { ko: '내역이 없습니다', en: 'No records found.' },
  totalValuation: { ko: '총 평가금액', en: 'Total Valuation' },
  fundNotes: [
    { ko: '총 투자기간이 1년 미만인 경우 연환산 수익률은 제공하지 않습니다.' , en: 'If the total investment period is less than one year, the annualized return is not provided.' },
    { ko: '총 투자원금에서 중간환매대금 및 수수료 보수를 차감하고 자산운용사가 운용한 결과가 평가금액입니다.', en: 'The amount remaining after subtracting interim redemptions and fees from the total investment principal, as managed by the asset manager, is the valuation amount.' },
    { ko: '적용법률이 종전의 「간접투자자산 운용업법(이하\'간투법)」인 경우에는 추가 판매가 금지됩니다.', en: 'If the applicable law is the former Indirect Investment Asset Management Act, additional sales are prohibited.' },
    {
      ko: '소규모펀드 안내사항', en: 'Notice for small funds',
      sub: [
        { ko: '자본시장법에 의해 설정되어 1년 이후 1개월간 계속하여 설정액이 50억원 미만인 공모펀드를 말하며 이러한 소규모펀드는 적정규모 미달로인해 분산투자가 어려워 수익률 등에 영향을 줄 수 있습니다.', en: 'A "small fund" refers to a publicly offered fund whose subscription amount has remained under 500 million KRW for one consecutive month after one year from establishment; this may affect returns due to insufficient diversification.' },
        { ko: '자본시장법 192조(투자신탁의 해지) 제 1항 및 자본시장법 시행령 제 223조 (승인이 면제되는 해지사유)에 의해 고객의사와 상관없이 임의해지가 가능하므로 유념하여 주시기 바랍니다.', en: 'Please note that under Article 192 of the Capital Markets Act and Article 223 of its Enforcement Decree, the fund may be terminated at any time regardless of the customer’s wishes.' },
      ],
    },
    { ko: '차감예상액은 기준시점의 평가금액으로 전액 환매했을 경우 발생할 것으로 예상되는 환매수수료와 세금, 성과보수 등을 합산한 금액이며, 일부 사모펀드의 경우 미지급 성과보수를 반영하지 않을 수 있습니다.', en: 'The estimated deduction is the sum of expected redemption fees, taxes, and performance fees if fully redeemed at the reference valuation; some private funds may not reflect unpaid performance fees.' },
    { ko: '연금저축계좌의 환매예상금액은 실제 출금시 세금, 위약시 적용기준가 등으로 인하여 달라질 수 있습니다.', en: 'The estimated redemption amount for pension savings accounts may differ due to taxes and applicable rates upon actual withdrawal.' },
    { ko: '"수수료, 보수"는 투자기간중 발생한 판매수수료 등 각종수수료 및 총 보수(판매보수, 운용보수, 신탁보수, 사무관리보수)입니다.', en: '"Fees & Commissions" refers to all sales fees incurred during the investment period and total commissions (sales, management, trust, and administrative commissions).' },
    { ko: '모든 예상액은 실제 환매 후와 차이가 발생할 수 있으니 참고 바랍니다.', en: 'All estimated amounts may differ from the actual amount after redemption.' },
    { ko: '이익분배금(현금배당)이 있는 펀드는 중간환매대금에 포함되며, 모든 예상액은 실제 환매 후와 차이가 발생할 수 있으니 참고 바랍니다.', en: 'Funds with profit distributions (cash dividends) include them in interim redemption amounts; all estimates may differ from the actual amount after redemption.' },
  ],
  overseasFundTit: { ko: '해외뮤추얼 펀드잔고 현황', en: 'Overseas Mutual Fund Balance Status' },
  overseasFundNotes: [
    { ko: '세전수익률은 세전평가이익 또는 세전평가손실을 매수원금과 대비하여 단순계산한 수익률이므로 펀드의 시장수익률과는 차이가 있을 수 있습니다.', en: 'The pre-tax return is a simple calculation against the purchase principal, so it may differ from the fund’s market return.' },
    { ko: '펀드는 「예금자보호법」의 적용을 받지 않으며, 실적배당상품으로 채권, 주식의 가격변동 및 환율변동 등에 따라 투자손실이 발생할 수 있습니다.', en: 'Funds are not covered by the Depositor Protection Act and, as performance-based products, may incur losses due to price and exchange rate fluctuations.' },
    { ko: '펀드잔고 현황에는 주식, 채권, RP, 예수금 등의 기타자산 및 투자일임계약(Wrap)으로 인한 펀드잔고는 표기되지 않습니다.', en: 'The fund balance status does not include other assets such as stocks, bonds, RPs, deposits, or fund balances from discretionary investment (Wrap) contracts.' },
  ],
  glossaryTit: { ko: '용어설명', en: 'Glossary' },
  glossary: [
    { term: { ko: '기준가', en: 'NAV' }, desc: { ko: '수익증권의 매입 또는 환매시 적용되는 가격으로 투자신탁의 순자산가치를 발행 수익증권 총수로 나누어 매일 산출되는 가격 입니다.', en: 'The price applied when buying or redeeming beneficiary certificates, calculated daily by dividing the trust’s net asset value by the total issued units.' } },
    { term: { ko: '투자원금', en: 'Investment Principal' }, desc: { ko: '해당 집합투자증권을 매수하기 위해 투자자가 납입한 금액의 누계(선취판매수수료로 납부한 금액 포함)', en: 'The cumulative amount paid by the investor to purchase the collective investment security (including front-end sales fees paid).' } },
    { term: { ko: '잔고좌수', en: 'Units Held' }, desc: { ko: '입출금거래의 결과로서 현재 투자자가 보유하게 되는 수익증권의 잔고량을 말합니다.', en: 'The balance of beneficiary certificate units currently held by the investor as a result of deposit/withdrawal transactions.' } },
    { term: { ko: '평가금액', en: 'Valuation Amount' }, desc: { ko: '수익증권, 국내뮤추얼→잔고좌수x기준가격÷거래단위(통상 1,000)\n해외뮤추얼→잔고좌수x기준가격x통화환율', en: 'Beneficiary certificates, domestic mutual → units held × NAV ÷ trading unit (usually 1,000)\nOverseas mutual → units held × NAV × exchange rate' } },
  ],
  guideTit: { ko: '금융거래시 주의사항', en: 'Notes on Financial Transactions' },
  guideItems: [
    { ko: '고객님의 거래내역 및 잔고를 확인하시고 이상이 있으실 경우 거래영업점으로 연락하여 주시기 바랍니다.', en: 'Please review your transaction history and balance, and contact your branch if you notice anything unusual.' },
    { ko: '안전한 금융거래를 위하여 계좌번호, 비밀번호, 기타 개인을 식별하기 위해 사용되는 이용자 번호가 제3자에게 유출되는 것을 방지하시고 비밀번호 등은 정기적으로 변경하여 주십시오. 특히 비밀번호가 노출된 것으로 의심되는 경우에는 즉시 거래영업점이나 고객지원센터(☎1588-0365)로 통보하여 주시기 바랍니다.', en: 'For safe transactions, please prevent your account number and password from being exposed, and change your password regularly. If exposure is suspected, notify your branch or the Customer Center (1588-0365) immediately.' },
    { ko: '통보지를 변경하시거나 E-mail 수신을 원하시는 경우에는 고객지원센터, 관리점으로 신청 또는 홈페이지, 모바일 앱, HTS에서 직접 변경 가능합니다.', en: 'To change your notification address or receive email notices, apply through the Customer Center, your branch, or change it directly via the website or mobile app/HTS.' },
    { ko: '손실보전계약(각서,차용증)에 의한 거래, 증권카드, 통장, 거래인감 등을 당사 직원에게 맡기시고 하는 거래는 불건전한 거래 관행으로 분쟁발생시 상당한 불이익을 받게 되오니 금하여 주십시오.', en: 'Transactions based on loss-compensation agreements or entrusting your securities card, passbook, or seal to our staff are unsound practices that may result in significant disadvantages in a dispute.' },
  ],
  detail: {
    seqNo: { ko: '순번', en: 'No.' },
    fundName: { ko: '펀드명', en: 'Fund Name' },
    currency: { ko: '통화', en: 'Currency' },
    units: { ko: '잔고좌수', en: 'Units Held' },
    unitSuffix: { ko: ' 좌', en: ' units' },
    firstInvestDate: { ko: '최초투자일자(기간)', en: 'First Investment Date (Period)' },
    principal: { ko: '투자원금', en: 'Investment Principal' },
    interimRedemption: { ko: '중간환매대금', en: 'Interim Redemption' },
    beforeCost: { ko: '비용차감 전', en: 'Before Cost' },
    afterCost: { ko: '비용차감 후', en: 'After Cost' },
    fees: { ko: '수수료 · 보수', en: 'Fees & Commissions' },
    feeRates: { ko: '판매수수료율,총보수율', en: 'Sales Fee Rate, Total Fee Rate' },
    valuation: { ko: '평가금액', en: 'Valuation Amount' },
    deductionExpected: { ko: '차감예상액', en: 'Estimated Deduction' },
    redemptionExpected: { ko: '환매예상금액', en: 'Estimated Redemption Amount' },
    cumulativeReturn: { ko: '누적수익률', en: 'Cumulative Return' },
    annualizedReturn: { ko: '연환산수익률', en: 'Annualized Return' },
    applicableLaw: { ko: '적용법률', en: 'Applicable Law' },
    smallFund: { ko: '소규모펀드', en: 'Small Fund' },
    buyPrincipal: { ko: '매수원금', en: 'Purchase Principal' },
    nav: { ko: '기준가', en: 'NAV' },
    preTaxValuation: { ko: '세전 평가금액', en: 'Pre-Tax Valuation' },
    preTaxReturn: { ko: '세전 수익률', en: 'Pre-Tax Return' },
  },
  close: { ko: '닫기', en: 'Close' },
  maxTitText: {
    ko: '평가금액은 {v} 원, 누적수익률은 {r} % 입니다.',
    en: 'The valuation amount is {v} KRW, and the cumulative return is {r}%.',
  },
};

export const sampleData = {
  customerName: { ko: '류원희', en: 'Wonhee Ryu' },
  accountNo: { ko: '001-01-191***', en: '001-01-191***' },
  balanceDate: { ko: '2024년 05월 31일', en: 'May 31, 2024' },
  funds: [
    {
      seqNo: '011',
      name: { ko: '하나UBS재편코어플러스증권[주식](C)', en: 'Hana UBS Reconstruction Core Plus Securities [Equity] (C)' },
      currency: { ko: 'KRW', en: 'KRW' },
      units: 3820000,
      firstInvestDate: { ko: '2021.03.15 (3년 2개월)', en: 'Mar 15, 2021 (3Y 2M)' },
      principal: 5000000,
      interimBeforeCost: 0,
      interimAfterCost: 0,
      fees: 32400,
      salesFeeRate: 1.0,
      totalFeeRate: 0.98,
      valuation: 5620300,
      deductionExpected: 16800,
      redemptionExpected: 5603500,
      cumulativeReturnBefore: 12.41,
      cumulativeReturnAfter: 12.07,
      annualizedReturnBefore: 3.86,
      annualizedReturnAfter: 3.75,
      applicableLaw: { ko: '자본시장법', en: 'Capital Markets Act' },
      smallFund: { ko: '해당없음', en: 'N/A' },
    },
    {
      seqNo: '035',
      name: { ko: '신한얼마사랑어린이적립식[주식](C5)', en: 'Shinhan Love-for-Kids Savings [Equity] (C5)' },
      currency: { ko: 'KRW', en: 'KRW' },
      units: 1250000,
      firstInvestDate: { ko: '2020.11.02 (3년 6개월)', en: 'Nov 2, 2020 (3Y 6M)' },
      principal: 1800000,
      interimBeforeCost: 0,
      interimAfterCost: 0,
      fees: 9800,
      salesFeeRate: 0,
      totalFeeRate: 0.85,
      valuation: 1954200,
      deductionExpected: 5200,
      redemptionExpected: 1949000,
      cumulativeReturnBefore: 8.56,
      cumulativeReturnAfter: 8.30,
      annualizedReturnBefore: 2.35,
      annualizedReturnAfter: 2.28,
      applicableLaw: { ko: '자본시장법', en: 'Capital Markets Act' },
      smallFund: { ko: '해당없음', en: 'N/A' },
    },
    {
      seqNo: '036',
      name: { ko: '신한상대가치장기증권자2[채권](C1)', en: 'Shinhan Relative-Value Long-Term Securities 2 [Bond] (C1)' },
      currency: { ko: 'KRW', en: 'KRW' },
      units: 950000,
      firstInvestDate: { ko: '2022.06.20 (1년 11개월)', en: 'Jun 20, 2022 (1Y 11M)' },
      principal: 850000,
      interimBeforeCost: 0,
      interimAfterCost: 0,
      fees: 3100,
      salesFeeRate: 0,
      totalFeeRate: 0.45,
      valuation: 891200,
      deductionExpected: 1800,
      redemptionExpected: 889400,
      cumulativeReturnBefore: 4.85,
      cumulativeReturnAfter: 4.72,
      annualizedReturnBefore: 2.51,
      annualizedReturnAfter: 2.44,
      applicableLaw: { ko: '자본시장법', en: 'Capital Markets Act' },
      smallFund: { ko: '해당없음', en: 'N/A' },
    },
  ],
  fundSum: 8465700,
  overseasFunds: [
    {
      seqNo: '008',
      name: { ko: '피델리티차이나포커스(A-USD)', en: 'Fidelity China Focus (A-USD)' },
      buyPrincipal: 14200000,
      nav: 18.42,
      units: 780000,
      preTaxValuation: 19472812,
      preTaxReturn: 37.13,
      currency: { ko: 'USD', en: 'USD' },
    },
  ],
  overseasFundSum: 19472812,
};
