// 실제 고객 데이터가 아닌, 화면 구조를 보여주기 위한 예시(더미) 데이터입니다.

export const text = {
  screenName: { ko: '퇴직연금 적립금운용현황보고서', en: 'Retirement Pension Fund Management Status Report' },
  summaryReportTit: { ko: '적립금 운용현황 보고서 (요약)', en: 'Fund Management Status Report (Summary)' },
  baseDateLabel: { ko: '작성기준일 : ', en: 'Prepared as of: ' },
  introSummary: {
    ko: '이 운용보고서 요약은 고객님이 가입하신 퇴직연금계좌의 비용, 실질수익률 등 주요정보를 제공하기 위한 것으로, ',
    en: 'This report summary provides key information such as costs and actual returns for your retirement pension account, ',
  },
  introSummaryHighlight: { ko: '계약 관련 상세내용은 본문', en: 'contract details in the main body' },
  introSummaryEnd: { ko: '에서 확인하실 수 있습니다.', en: '.' },
  basicInfoTit: { ko: '기본정보', en: 'Basic Information' },
  subscriber: { ko: '가입자(또는 사업장)', en: 'Subscriber (or Workplace)' },
  contractDate: { ko: '가입(계약)일자', en: 'Contract Date' },
  planType: { ko: '제도유형', en: 'Plan Type' },
  company: { ko: '가입자 소속회사', en: 'Subscriber’s Company' },
  pensionAvailableDate: { ko: '연금수령개시 가능일', en: 'Pension Payout Eligibility Date' },
  keyInfoTit: { ko: '주요정보', en: 'Key Information' },
  keyInfoText: {
    ko: '정보고시 시점인 ({baseDate}) 기준으로 고객님께서 가입하신 퇴직연금계좌에 납부한 납입원금 합계액은 (',
    en: 'As of the notice date ({baseDate}), the total contributions to your retirement pension account are (',
  },
  keyInfoMid1: { ko: ' 원)이며, 적립금(평가금액)은 (', en: ' KRW), the accrued balance (valuation) is (' },
  keyInfoMid2: { ko: ' 원), 누적수익률은 (', en: ' KRW), and the cumulative return is (' },
  keyInfoEnd: { ko: ' %) 입니다.', en: '%).' },
  contribution: { ko: '납입원금', en: 'Contributions' },
  investProfit: { ko: '운용손익', en: 'Investment Profit/Loss' },
  withdrawalEtc: { ko: '중도인출금 등*', en: 'Interim Withdrawals, etc.*' },
  withdrawalNote: { ko: '* 중도인출, 연금지급, 퇴직급여 지급, 제도전환 등', en: '* Interim withdrawal, pension payment, severance payment, plan conversion, etc.' },
  feeAmount: { ko: '수수료 금액*', en: 'Fee Amount*' },
  feeNote: { ko: '* DC 및 기업형IRP의 경우, 기업(사용자)이 별도로 납부해야 하는 수수료는 포함하지 않습니다. (이하, 수익률 계산시 동일)', en: '* For DC and corporate IRP plans, fees separately paid by the employer are not included (applies to return calculations below).' },
  balanceExplain: {
    ko: '납입원금 ①과 운용손익 ②의 합계에서 중도인출금 등 ③ 및 수수료 금액 ④을 차감한 결과가 적립금(평가금액) ⑤ 입니다.',
    en: 'The result after subtracting interim withdrawals ③ and fees ④ from the sum of contributions ① and investment profit ② is the accrued balance ⑤.',
  },
  accruedBalance: { ko: '적립금(평가금액)', en: 'Accrued Balance (Valuation)' },
  cumulativeReturnAfterFee: { ko: '누적수익률(수수료 차감 후)', en: 'Cumulative Return (After Fees)' },
  annualAvgReturn: { ko: '연평균수익률*', en: 'Annualized Average Return*' },
  keyInfoNote1: { ko: '최초 부담금 납입 후 1년이상 경과한 계약에 한하여 연평균 수익률을 안내해 드립니다.', en: 'The annualized return is provided only for contracts more than one year after the first contribution.' },
  keyInfoNote2: { ko: '최초 입금일부터 기준일까지의 금액을 표기했습니다.', en: 'Shows the amount from the first deposit date to the base date.' },
  bodyReportTit: { ko: '적립금 운용현황 보고서 (본문)', en: 'Fund Management Status Report (Main Body)' },
  baseDate2: { ko: '기준일자', en: 'Base Date' },
  subscriberOrWorkplace: { ko: '가입자(또는 사업장)', en: 'Subscriber (or Workplace)' },
  affiliatedCompany: { ko: '소속회사', en: 'Affiliated Company' },
  contact: { ko: '연락처(휴대폰/이메일)', en: 'Contact (Mobile/Email)' },
  contactNote: { ko: '상기 연락처가 변경되는 경우 통지하여 주시기 바랍니다.(퇴직연금 고객센터 : 1588-1122)', en: 'Please notify us if the above contact information changes. (Retirement Pension Customer Center: 1588-1122)' },
  s1Tit: { ko: 'I. 자산현황', en: 'I. Asset Status' },
  s1_1Tit: { ko: '1. 적립금 현황', en: '1. Accrued Balance Status' },
  priorBalance: { ko: '전기말 적립금*(A)', en: 'Prior Period-End Balance* (A)' },
  paymentAmount: { ko: '납입액(B)', en: 'Contribution (B)' },
  companyPayment: { ko: '회사납입', en: 'Company Contribution' },
  subscriberPayment: { ko: '가입자납입', en: 'Subscriber Contribution' },
  deductionAmount: { ko: '차감액(C)', en: 'Deduction (C)' },
  feeDeduction: { ko: '수수료', en: 'Fee' },
  withdrawalDeduction: { ko: '중도인출 등', en: 'Interim Withdrawal, etc.' },
  investProfitD: { ko: '운용손익(D)', en: 'Investment Profit/Loss (D)' },
  currentBalance: { ko: '당기말 적립금**(A+B)-(C+D)', en: 'Current Period-End Balance** (A+B)-(C+D)' },
  s1_1Note1: { ko: '전년도 말 일자 기준 적립금', en: 'Balance as of the end of the prior year.' },
  s1_1Note2: { ko: '기준일자의 적립금', en: 'Balance as of the base date.' },
  s1_2Tit: { ko: '2. 납입 및 차감 세부내역', en: '2. Contribution and Deduction Details' },
  s1_2aTit: { ko: '(1) 납입액(부담금)', en: '(1) Contributions' },
  unitWon: { ko: '(단위:원)', en: '(Unit: KRW)' },
  companyPaymentAmount: { ko: '회사 납입액', en: 'Company Contribution' },
  subscriberPaymentAmount: { ko: '가입자 납입액', en: 'Subscriber Contribution' },
  paymentDate: { ko: '납입일자', en: 'Contribution Date' },
  paymentAmountCol: { ko: '납입금액', en: 'Amount' },
  noResult: { ko: '내역이 없습니다', en: 'No records found.' },
  more: { ko: '더보기', en: 'More' },
  less: { ko: '접기', en: 'Collapse' },
  companyPaymentSum: { ko: '회사 납입액 합계', en: 'Total Company Contribution' },
  subscriberPaymentSum: { ko: '가입자 납입액 합계', en: 'Total Subscriber Contribution' },
  s1_2aNote: { ko: '* 당사 또는 타사로부터 이전된 사용자부담금의 경우 납입원금 및 운용손익이 포함된 금액입니다.', en: '* For employer contributions transferred from us or another company, the amount includes contributions and investment returns.' },
  s1_2bTit: { ko: '(2) 차감액(수수료·중도인출 등)', en: '(2) Deductions (Fees, Interim Withdrawals, etc.)' },
  feeTit: { ko: '수수료', en: 'Fee' },
  detailItem: { ko: '세부항목*', en: 'Detail Item*' },
  deductionDate: { ko: '차감일자', en: 'Deduction Date' },
  deductionAmountCol: { ko: '차감금액', en: 'Amount' },
  deductionSum: { ko: '차감액 합계', en: 'Total Deductions' },
  s1_2bNote: { ko: '* 운용관리수수료, 자산관리수수료, 펀드 판매수수료', en: '* Management fee, custodial fee, fund sales fee.' },
  withdrawalTit: { ko: '중도인출금 등', en: 'Interim Withdrawal, etc.' },
  detailItem2: { ko: '세부항목**', en: 'Detail Item**' },
  withdrawalSum: { ko: '중도인출금 등 합계', en: 'Total Interim Withdrawals' },
  s1_2cNote: { ko: '중도인출, 연금지급, 퇴직급여 지급, 제도전환 등', en: 'Interim withdrawal, pension payment, severance payment, plan conversion, etc.' },
  s1_3Tit: { ko: '3. 보유 상품현황', en: '3. Holdings Status' },
  totalPrefix: { ko: '총 ', en: 'Total: ' },
  totalSuffix: { ko: '건', en: ' items' },
  unitWonPercent: { ko: '(단위:원, %)', en: '(Unit: KRW, %)' },
  col: {
    division: { ko: '구분', en: 'Category' },
    productName: { ko: '상품명', en: 'Product Name' },
    buyPrincipal: { ko: '매입원금*', en: 'Purchase Principal*' },
    profitLoss: { ko: '평가손익**', en: 'Valuation Profit/Loss**' },
    valuation: { ko: '평가금액***', en: 'Valuation***' },
    weight: { ko: '비중', en: 'Weight' },
  },
  valuationSum: { ko: '평가금액 합계', en: 'Total Valuation' },
  s1_3Notes: [
    { ko: '* 납입 후 상품으로 매입된 금액(예금만기재예치 또는 교체매매 후)', en: '* Amount purchased into a product after contribution (upon deposit rollover or reallocation).' },
    { ko: '** 평가손익 = 평가금액-매입원금', en: '** Valuation Profit/Loss = Valuation − Purchase Principal' },
    { ko: '*** 기준일자의 평가금액', en: '*** Valuation as of the base date.' },
    { ko: '**** 상기 내역은 상품별 적립금 상위 15건만 나열하였으며, 그 외 상품은 신한투자증권 홈페이지(https://www.shinhansec.com/) 또는 신한 SOL증권 앱을 통해 확인이 가능합니다.', en: '**** Only the top 15 holdings by balance are listed; others can be checked on the Shinhan Investment Corp. website or the Shinhan SOL Securities app.' },
    { ko: '***** 퇴직연금 총 위험자산 투자한도는 70%를 초과할 수 없습니다. 또한 집중투자로 인한 위험을 방지하기 위해 동일법인 등이 발행한 증권의 투자한도는 DB 10%, DC/IRP 30%를 초과할 수 없습니다.', en: '***** The total risk-asset investment limit for retirement pensions cannot exceed 70%. To prevent concentration risk, investment in securities issued by the same entity cannot exceed 10% for DB or 30% for DC/IRP.' },
  ],
  s2Tit: { ko: 'II. 수익률 현황', en: 'II. Return Status' },
  s2_1Tit: { ko: '1. 전체 수익률 현황', en: '1. Overall Return Status' },
  cumulativeReturnLabel: { ko: '누적수익률*', en: 'Cumulative Return*' },
  annualAvgReturnLabel: { ko: '연평균수익률**', en: 'Annualized Average Return**' },
  s2_1Notes: [
    { ko: '누적수익률 = {적립금(평가금액) + 중도인출금 등} / 납입원금 - 1', en: 'Cumulative Return = {Accrued Balance + Interim Withdrawals} / Contributions − 1' },
    { ko: '연평균수익률(기하평균) = (1+가입 이후 누적수익률)^(1/가입년수) - 1 (단, 최초입금일 이후(전액 중도인출이 있는 경우는 인출 후 최초입금일 이후) 기간이 1년 미만인 경우 연평균수익률을 표시하지 않습니다.)', en: 'Annualized Average Return (geometric mean) = (1 + cumulative return since signup) ^ (1/years) − 1 (not shown if under 1 year).' },
  ],
  s2_2Tit: { ko: '2. 상품별 금리/수익률 현황', en: '2. Rate/Return Status by Product' },
  s2_2aTit: { ko: '(1) 원리금보장형', en: '(1) Principal-Guaranteed' },
  unitPercent: { ko: '(단위:%)', en: '(Unit: %)' },
  col2: {
    productName: { ko: '상품명', en: 'Product Name' },
    rate: { ko: '금리', en: 'Rate' },
    buyDate: { ko: '매수일자', en: 'Purchase Date' },
    maturityDate: { ko: '만기예정일', en: 'Expected Maturity Date' },
  },
  s2_2aNotes: [
    { ko: '원리금보장상품은 만기예정일 1영업일 전까지 별도의 의사표시가 없을 경우 현금성자산으로 상환됩니다.', en: 'Principal-guaranteed products are redeemed as cash equivalents if no instruction is given by 1 business day before maturity.' },
    { ko: '사전지정운용방법(디폴트옵션)을 등록하신 경우, 4주 동안 별도의 운용지시가 없다면 등록된 연락처로 사전지정운용상품으로 운용될 예정임을 안내 드리며, 2주 후 매수됩니다.', en: 'If you have registered a default investment option, you will be notified if no instruction is given within 4 weeks, and the default product will be purchased after 2 more weeks.' },
  ],
  s2_2bTit: { ko: '(2) 실적배당형', en: '(2) Performance-Based' },
  col3: {
    productName: { ko: '상품명', en: 'Product Name' },
    investPeriod: { ko: '투자기간', en: 'Investment Period' },
    cumulativeReturn: { ko: '누적수익률', en: 'Cumulative Return' },
    annualizedReturn: { ko: '연환산수익률(1년 이상 운용상품)', en: 'Annualized Return (1yr+ products)' },
  },
  s2_2bNote: { ko: '※ ETF는 체결기준, 그 외 실적배당형 상품은 결제기준으로 투자기간을 명시하였습니다.', en: '※ Investment periods for ETFs are trade-date basis; other performance-based products use settlement-date basis.' },
  s3Tit: { ko: 'III. 수수료 등 비용 안내', en: 'III. Fee and Cost Information' },
  s3_1Tit: { ko: '1. 수수료 부과 기준', en: '1. Fee Basis' },
  feeDiscountTit: { ko: '퇴직연금 수수료 할인/면제 안내', en: 'Retirement Pension Fee Discount/Exemption Guide' },
  col4: {
    division: { ko: '구분', en: 'Category' },
    applicable: { ko: '해당사항', en: 'Applicable' },
    plan: { ko: '적용 제도', en: 'Plan' },
    mgmtDiscount: { ko: '운용관리 수수료', en: 'Management Fee' },
    custodyDiscount: { ko: '자산관리 수수료', en: 'Custody Fee' },
    note: { ko: '비고', en: 'Note' },
  },
  discountLabel: { ko: '할인', en: 'Discount' },
  exemptLabel: { ko: '면제', en: 'Exempt' },
  feeDiscountRows: [
    { division: { ko: '할인', en: 'Discount' }, applicable: { ko: '장기계약', en: 'Long-term Contract' }, plan: { ko: 'DB', en: 'DB' }, rate: { ko: '2~4차년도: 10%\n5~10차년도: 18%\n11차년도 이후: 20%', en: 'Yr 2-4: 10%\nYr 5-10: 18%\nYr 11+: 20%' }, note: { ko: '최초부담금 납입일로부터 기산', en: 'Calculated from the first contribution date.' } },
    { division: { ko: '할인', en: 'Discount' }, applicable: { ko: '장기계약', en: 'Long-term Contract' }, plan: { ko: 'DC', en: 'DC' }, rate: { ko: '2~4차년도: 10%\n5~10차년도: 15%\n11차년도 이후: 20%', en: 'Yr 2-4: 10%\nYr 5-10: 15%\nYr 11+: 20%' }, note: { ko: '', en: '' } },
    { division: { ko: '할인', en: 'Discount' }, applicable: { ko: '강소기업', en: 'Promising SME' }, plan: { ko: 'DB, DC', en: 'DB, DC' }, rate: { ko: '50%', en: '50%' }, note: { ko: '별도 신청 필요', en: 'Application required.' } },
    { division: { ko: '할인', en: 'Discount' }, applicable: { ko: '사회복지법인/시설', en: 'Social Welfare Corp/Facility' }, plan: { ko: 'DB, DC', en: 'DB, DC' }, rate: { ko: '50%', en: '50%' }, note: { ko: '별도 신청 필요', en: 'Application required.' } },
    { division: { ko: '할인', en: 'Discount' }, applicable: { ko: '중소기업', en: 'SME' }, plan: { ko: 'DB, DC', en: 'DB, DC' }, rate: { ko: '10%', en: '10%' }, note: { ko: '별도 신청 필요(중소기업 확인서 발급 기업)', en: 'Application required (SME certificate holders).' } },
    { division: { ko: '면제', en: 'Exempt' }, applicable: { ko: '적립금 구분 무관', en: 'Regardless of Balance Type' }, plan: { ko: 'IRP', en: 'IRP' }, rate: { ko: '면제', en: 'Exempt' }, note: { ko: '', en: '' } },
    { division: { ko: '면제', en: 'Exempt' }, applicable: { ko: '개인추가납입금', en: 'Individual Additional Contribution' }, plan: { ko: 'DC', en: 'DC' }, rate: { ko: '면제', en: 'Exempt' }, note: { ko: '', en: '' } },
    { division: { ko: '면제', en: 'Exempt' }, applicable: { ko: '집합투자증권(실적배당형 보험 포함)', en: 'Collective Investment Securities (incl. Performance-Based Insurance)' }, plan: { ko: 'DB', en: 'DB' }, rate: { ko: '면제', en: 'Exempt' }, note: { ko: '', en: '' } },
  ],
  s3_1Notes: [
    { ko: 'DB의 수수료는 적립금에서 자동 차감합니다. DC의 수수료는 회사에서 별도로 수수료를 입금하여 처리됩니다.', en: 'DB fees are automatically deducted from the balance. DC fees are separately deposited by the company.' },
    { ko: '적립금을 집합투자증권(펀드)으로 운용하는 경우에는 아래의 펀드보수가 추가로 발생(적립금 차감)할 수 있습니다.', en: 'If the balance is invested in collective investment securities (funds), the fund fees below may additionally apply.' },
    { ko: '2024년 04월 01일 IRP 수수료 모두 면제 적용', en: 'IRP fees fully exempted starting April 1, 2024.' },
  ],
  s3_2Tit: { ko: '2. 펀드상품의 보수 현황', en: '2. Fund Fee Status' },
  col5: {
    productName: { ko: '상품명', en: 'Product Name' },
    totalFeeRate: { ko: '총보수율(%)', en: 'Total Fee Rate (%)' },
    feePer100: { ko: '적립금 100원당 총보수액(원)', en: 'Total Fee per 100 KRW Balance (KRW)' },
  },
  s3_2Notes: [
    { ko: '원리금보장형 상품에는 상품 수수료·보수가 부과되지 않습니다.', en: 'Principal-guaranteed products are not charged product fees.' },
    { ko: '상기 내역은 상품별 적립금 상위 15건만 나열하였으며, 그 외 상품은 신한투자증권 홈페이지 또는 신한 SOL증권 앱을 통해 확인이 가능합니다.', en: 'Only the top 15 holdings by balance are listed; others can be checked on the website or app.' },
  ],
  s4Tit: { ko: 'IV. 기타사항', en: 'IV. Other Matters' },
  s4_1Tit: { ko: '1. 예상 연금수령액', en: '1. Expected Pension Payout' },
  s4_1Notes: [
    { ko: '예상연금수령액은 향후 세금, 납입내역, 수익률, 연금수령방법 등에 따라 실제 연금수령액과 다를 수 있습니다.', en: 'The estimated pension payout may differ from the actual amount based on future taxes, contribution history, returns, and payout method.' },
    { ko: '실제로 연금을 수령하기 위해서는 연금수령 개시신청 가능일 이후에 영업점을 방문하거나 금융회사 홈페이지를 통해 "연금 수령개시 신청서" 등 관련 서류를 제출하여야 합니다.', en: 'To actually receive the pension, you must submit related documents at a branch or via the website after the eligibility date.' },
    { ko: "'통합연금포털(https://100lifeplan.fss.or.kr)' 방문시 국민연금, 연금저축 등 개인별 연금 가입현황을 확인하실 수 있습니다.", en: 'Visit the "Integrated Pension Portal" to check your National Pension, pension savings, and other pension subscriptions.' },
  ],
  expectedContribution: { ko: '(가정)예상 납입액', en: '(Assumed) Expected Contribution' },
  expectedReturn: { ko: '(가정)예상 수익률', en: '(Assumed) Expected Return' },
  col6: {
    age: { ko: '연령(만)', en: 'Age' },
    year: { ko: '연도', en: 'Year' },
    amount: { ko: '금액', en: 'Amount' },
  },
  ageSuffix: { ko: '세', en: '' },
  yearSuffix: { ko: ' 년', en: '' },
  s4_1FooterNotes: [
    { ko: '예상 납입액 : 작성기준일로부터 역산한 직전 3년간의 월평균 납입액을 의미합니다.', en: 'Expected Contribution: the average monthly contribution over the past 3 years from the base date.' },
    { ko: '예상 수익률 : \'통합연금포털\' 예상연금액 산출시 적용되는 가정수익률을 적용하였으며, 매년 변경될 수 있습니다.', en: 'Expected Return: the assumed return rate used by the "Integrated Pension Portal," which may change yearly.' },
  ],
  s4_2Tit: { ko: '2. 계좌이체 제도 안내', en: '2. Account Transfer System Guide' },
  s4_2Warning: { ko: '관련 세법 개정으로 계좌이체 제도 내용이 달라질 수 있음에 주의하시기 바랍니다.', en: 'Please note that the account transfer system may change due to related tax law revisions.' },
  s4_2Notes: [
    { ko: '계좌이체 제도는 소득세법 시행령 제40조의4(연금계좌의 이체)에 따라 기존 연금계좌에 있는 금액이 연금수령이 개시되기 전의 다른 연금계좌로 이체되는 경우 이를 인출로 보지 않고 계속 세액공제나 과세이연 혜택을 유지시키는 것을 의미합니다.', en: 'The account transfer system allows funds to move between pension accounts before payout begins without being treated as a withdrawal, preserving tax benefits.' },
    { ko: '계좌이체는 전부 이전만 가능하고, 일부 금액의 이전은 불가합니다.', en: 'Only full transfers are allowed; partial transfers are not permitted.' },
  ],
  s4_2Portal: {
    ko: "'통합연금포털(https://100lifeplan.fss.or.kr)'의 '퇴직연금 통합공시' 메뉴를 통해 퇴직연금사업자별 퇴직연금 수익률, 총비용부담률 등을 비교해 보실 수 있습니다.",
    en: 'Compare retirement pension returns and total cost rates by provider via the "Integrated Pension Portal."',
  },
  companyName: { ko: '신한투자증권주식회사', en: 'Shinhan Investment Corp.' },
  customerCenter: { ko: '퇴직연금 고객센터(1588-1122)', en: 'Retirement Pension Center (1588-1122)' },
};

function genPensionSchedule() {
  const rows = [];
  for (let age = 55; age <= 90; age += 1) {
    rows.push({ age, year: 2024 + (age - 55), amount: Math.round((2100000 + (age - 55) * 12000) / 100) * 100 });
  }
  return rows;
}

export const sampleData = {
  baseDate: '2024.05.31',
  subscriber: { ko: '류원희', en: 'Wonhee Ryu' },
  contractDate: '2016.07.01',
  planType: { ko: 'DC(확정기여형)', en: 'DC (Defined Contribution)' },
  company: { ko: '신한투자증권', en: 'Shinhan Investment Corp.' },
  pensionAvailableDate: '2029.07.01',
  contribution: 42000000,
  investProfit: 6820000,
  withdrawalEtc: 0,
  feeAmount: 168400,
  accruedBalance: 48651600,
  cumulativeReturn: 15.84,
  annualAvgReturn: 2.42,
  contact: { ko: '010-****-5678 / w****@shinhan.com', en: '010-****-5678 / w****@shinhan.com' },
  priorBalance: 45200000,
  companyPaymentTotal: 3200000,
  subscriberPaymentTotal: 0,
  feeDeductionTotal: 42100,
  withdrawalDeductionTotal: 0,
  investProfitD: 291700,
  currentBalance: 48651600,
  payments: [
    { companyDate: '2024.03.25', companyAmount: 1050000, subscriberDate: '-', subscriberAmount: 0 },
    { companyDate: '2024.04.25', companyAmount: 1075000, subscriberDate: '-', subscriberAmount: 0 },
    { companyDate: '2024.05.25', companyAmount: 1075000, subscriberDate: '-', subscriberAmount: 0 },
  ],
  fees: [
    { item: { ko: '운용관리수수료', en: 'Management Fee' }, date: '2024.05.31', amount: 21050 },
    { item: { ko: '자산관리수수료', en: 'Custody Fee' }, date: '2024.05.31', amount: 21050 },
  ],
  withdrawals: [],
  holdings: [
    { division: { ko: '실적배당형', en: 'Performance-Based' }, name: { ko: '신한 TDF2045', en: 'Shinhan TDF2045' }, buyPrincipal: 30000000, profitLoss: 4820000, valuation: 34820000, weight: 71.6 },
    { division: { ko: '원리금보장형', en: 'Principal-Guaranteed' }, name: { ko: 'ELB 정기예금형', en: 'ELB Time Deposit Type' }, buyPrincipal: 12000000, profitLoss: 2000000, valuation: 13831600, weight: 28.4 },
  ],
  holdingSum: 48651600,
  overallCumulativeReturn: 15.84,
  overallAnnualReturn: 2.42,
  periodFrom: '2016.07.01',
  periodTo: '2024.05.31',
  guaranteedProducts: [
    { name: { ko: 'ELB 정기예금형', en: 'ELB Time Deposit Type' }, rate: 3.25, buyDate: '2024.02.15', maturityDate: '2025.02.15' },
  ],
  performanceProducts: [
    { name: { ko: '신한 TDF2045', en: 'Shinhan TDF2045' }, periodFrom: '2016.07.01', periodTo: '2024.05.31', cumulativeReturn: 22.16, annualizedReturn: 2.51 },
  ],
  fundFees: [
    { name: { ko: '신한 TDF2045', en: 'Shinhan TDF2045' }, totalFeeRate: 0.52, feePer100: 0.052 },
  ],
  expectedContribution: 1075000,
  expectedReturn: 3.2,
  pensionSchedule: genPensionSchedule(),
};
