// 실제 고객 데이터가 아닌, 화면 구조를 보여주기 위한 예시(더미) 데이터입니다.

export const text = {
  screenName: { ko: '특정금전신탁 운용보고서', en: 'Specific Money Trust Management Report' },
  greetingAfter: { ko: '님 안녕하세요.', en: '.' },
  introText: {
    ko: '{baseDate} 기준, {accountNo} 계좌 잔고내역입니다.',
    en: 'This is the balance detail for account {accountNo} as of {baseDate}.',
  },
  accountProfitTit: { ko: '계좌 수익안내', en: 'Account Profit Information' },
  principal: { ko: '원본금액', en: 'Principal Amount' },
  afterTaxProfitSum: { ko: '세후이익합계', en: 'Total After-Tax Profit' },
  fundProfitTit: { ko: '신탁펀드별 수익안내', en: 'Profit Information by Trust Fund' },
  unitWon: { ko: '(단위:원)', en: '(Unit: KRW)' },
  totalPrefix: { ko: '총 ', en: 'Total: ' },
  totalSuffix: { ko: '건', en: ' items' },
  col: {
    seqNo: { ko: '순번', en: 'No.' },
    fundName: { ko: '신탁펀드명', en: 'Trust Fund Name' },
    principalAmount: { ko: '원본금액', en: 'Principal' },
    operatingProfit: { ko: '운용수익', en: 'Operating Profit' },
    contractDate: { ko: '계약일', en: 'Contract Date' },
    details: { ko: '상세보기', en: 'Details' },
    fundEvalMethod: { ko: '펀드평가방법', en: 'Fund Valuation Method' },
    afterTaxProfit: { ko: '세후이익', en: 'After-Tax Profit' },
    maturityDate: { ko: '만기일', en: 'Maturity Date' },
  },
  noResult: { ko: '내역이 없습니다', en: 'No records found.' },
  more: { ko: '더보기', en: 'More' },
  less: { ko: '접기', en: 'Collapse' },
  principalSum: { ko: '원본금액 합계', en: 'Total Principal' },
  trustFeeSum: { ko: '신탁보수 합계', en: 'Total Trust Fee' },
  taxSum: { ko: '세금 합계', en: 'Total Tax' },
  operatingProfitSum: { ko: '운용수익 합계', en: 'Total Operating Profit' },
  afterTaxSum: { ko: '세후이익 합계', en: 'Total After-Tax Profit' },
  fxNote: {
    ko: '설정통화가 외화인 경우, 원화환산으로 표기되며 신탁보수 및 제비용은 만기 시 실제금액과 상이할 수 있습니다.',
    en: 'If the settlement currency is foreign, amounts are shown converted to KRW, and trust fees/expenses may differ from the actual amount at maturity.',
  },
  assetTit: { ko: '신탁펀드별 편입자산 안내', en: 'Included Assets by Trust Fund' },
  col2: {
    seqNo: { ko: '순번', en: 'No.' },
    fundName: { ko: '신탁펀드명', en: 'Trust Fund Name' },
    securityName: { ko: '종목명', en: 'Security Name' },
    evalAmount: { ko: '평가금액', en: 'Valuation' },
    details: { ko: '상세보기', en: 'Details' },
  },
  detail: {
    seqNo: { ko: '순번', en: 'No.' },
    fundName: { ko: '신탁펀드명', en: 'Trust Fund Name' },
    principalAmount: { ko: '원본금액', en: 'Principal' },
    operatingProfit: { ko: '운용수익', en: 'Operating Profit' },
    trustFee: { ko: '신탁보수', en: 'Trust Fee' },
    tax: { ko: '세금', en: 'Tax' },
    afterTaxProfit: { ko: '세후이익', en: 'After-Tax Profit' },
    contractMaturity: { ko: '계약일/만기일', en: 'Contract/Maturity Date' },
    fundEvalMethod: { ko: '펀드평가방법', en: 'Fund Valuation Method' },
    settlementCurrency: { ko: '설정통화', en: 'Settlement Currency' },
    assetDivision: { ko: '자산구분', en: 'Asset Category' },
    securityName: { ko: '종목명', en: 'Security Name' },
    buyAmount: { ko: '매입금액', en: 'Purchase Amount' },
    evalAmount: { ko: '평가금액', en: 'Valuation' },
    buyReturn: { ko: '매입수익률', en: 'Purchase Return' },
    marketReturn: { ko: '시가수익률', en: 'Market Return' },
    creditRating: { ko: '신용등급', en: 'Credit Rating' },
  },
  guideTit: { ko: '금융거래시 주의사항', en: 'Notes on Financial Transactions' },
  guideItems: [
    { ko: '고객님의 신탁운용보고서를 확인하시고 이상이 있으실 경우 거래영업점으로 연락 및 상담하여 주시기 바랍니다.', en: 'Please review your trust management report and contact your branch if you notice anything unusual.' },
    { ko: '안전한 금융거래를 위하여 계좌번호, 비밀번호, 기타 개인을 식별하기 위해 사용되는 이용자 번호가 제 3자에게 유출되는 것을 방지하시고, 비밀번호 등은 정기적으로 변경하셔야 합니다. 특히 비밀번호가 노출된 것으로 의심되는 경우에는 즉시 거래영업점이나 고객상담센터(1588-0365)로 통보하여 주시기 바랍니다.', en: 'For safe financial transactions, please prevent your account number, password, and other identifying user information from being exposed to third parties, and change your password regularly. If you suspect exposure, notify your branch or the Customer Center (1588-0365) immediately.' },
    { ko: '주소가 변경된 경우 반드시 주소변경을 신청하여 주십시오.', en: 'If your address has changed, please be sure to update it.' },
    { ko: '손실보전계약(각서,차용증)에 의한 거래, 증권카드, 통장, 거래인감 등을 당사 직원에게 위탁하여 진행되는 거래는 불건전한 관행으로 분쟁 발생시 상당한 불이익을 받게 되오니 금하여 주십시오.', en: 'Transactions based on loss-compensation agreements or entrusting your securities card, passbook, or seal to our staff are unsound practices that may result in significant disadvantages in a dispute, so please refrain from them.' },
    { ko: '당사는 신탁업자로서 신탁계약서 제 17조(신탁의 종료)에 따라 신탁기간이 종료된 이후, 신탁재산을 운용현상대로 교부하기가 곤란하거나 현금화하기 어려운 경우 현금 교부가 가능해 질 때까지 신탁재산의 관리의무(보관, 관리 및 추심)을 계속하고 있습니다.', en: 'As trustee, under Article 17 (Termination of Trust) of the trust agreement, we continue our custody/management duties for trust assets after the trust period ends if delivery in kind or liquidation is difficult, until cash delivery becomes possible.' },
    { ko: '신탁상품 중 원리금 상환지연 등으로 자산의 평가가격(*) 등이 제공되지 않는 경우 가장 최근 시점에 평가된 가격을 기초로 제공합니다. 따라서, 현재 평가금액이 상환 가능금액을 의미하는 것은 아니며 실제 상환금액은 평가금액과 상이할 수 있습니다.* 평가금액은 ①민간평가회사에서 산정한 기준가격 또는 ②발행사에서 제공한 이론가격 또는 ③운용사에서 제공한 기준가격을 의미합니다.', en: 'If a valuation price is unavailable for a trust product due to delayed principal/interest repayment, the most recently valued price is used. The current valuation does not necessarily represent the redeemable amount, and the actual redemption amount may differ. * Valuation refers to (1) the base price from a private valuation firm, (2) the theoretical price from the issuer, or (3) the base price from the asset manager.' },
    { ko: '신탁자산 평가방법이 장부가 평가일 경우 해당 기준일의 장부가격으로 평가되어, 현시점의 시장가치와는 차이가 발생할 수 있습니다. 시가 평가를 원하시는 경우 해당 지점으로 문의하여 주시기 바랍니다.', en: 'If the trust asset valuation method is book value, it is valued at the book price as of the base date, which may differ from current market value. Please contact your branch if you prefer market valuation.' },
    { ko: '신탁계약은 위탁자의 운용지시에 따라 운용되는 실적배당형으로 관계법령에 의거 고객에게 확정된 수익을 제공하지 않습니다. 본 보고서는 기준일 현재 평가방법에 따른 운용현황을 나타낼 뿐 최종 상환금액을 의미하지 않으며, 시장상황 및 편입자산의 구성에 따라 운용현황금액과 상환금액의 차이가 발생할 수 있습니다.', en: 'The trust is a performance-based product managed per the settlor’s instructions and does not guarantee a fixed return under applicable law. This report shows the management status per the valuation method as of the base date only, not the final redemption amount, which may differ depending on market conditions and asset composition.' },
    { ko: '본 보고서는 회사의 공식적인 잔고(거래)증명서 양식이 아니므로 대외기관 등에 제출용도로 사용할 수 없으며, 회사의 공식 잔고(거래)증명서를 원하는 고객께서는 영업점 고객지원팀에 발급을 의뢰하거나 별도로 회사가 정한 절차를 이용하여 주시기 바랍니다. 본 전자문서는 고객의 금융거래정보가 포함되어 있으므로 정보유출로 인한 피해가 발생하지 않도록 유의하여 주시기 바랍니다.', en: 'This report is not an official balance (transaction) certificate and cannot be submitted to external institutions; customers needing an official certificate should request one from their branch support team. This electronic document contains your financial transaction information, so please take care to prevent information leakage.' },
    { ko: '비상장주식 및 기타 시가평가가 어려운 자산의 경우, 기업회계기준서에 따라 취득원가(장부가)로 평가됩니다. 따라서 해당 자산을 편입하고 있는 신탁의 경우 평가가격은 실제가치와 다를 수 있습니다. 또한 이슈가 발생한 상품의 경우에도 취득원가(장부가)로 평가될 수 있으며, 이는 실제가치를 반영하고 있지 않습니다.', en: 'Unlisted stocks and other hard-to-value assets are valued at acquisition cost (book value) per accounting standards. Trusts holding such assets may have valuation prices that differ from actual value. Products with issues may also be valued at acquisition cost, which does not reflect actual value.' },
  ],
};

export const sampleData = {
  customerName: { ko: '류원희', en: 'Wonhee Ryu' },
  baseDate: '2024.05.31',
  accountNo: { ko: '20385174**', en: '20385174**' },
  principal: 87300000,
  afterTaxProfitSum: 0,
  funds: [
    {
      seqNo: 1,
      name: { ko: '부산 중앙M리츠B', en: 'Busan Jungang M REITs B' },
      principal: 48500000,
      operatingProfit: 0,
      contractDate: '2019.04.15',
      evalMethod: { ko: '시가', en: 'Market Value' },
      afterTaxProfit: 0,
      maturityDate: '2024.07.31',
      trustFee: 0,
      tax: 0,
      settlementCurrency: { ko: 'KRW', en: 'KRW' },
    },
    {
      seqNo: 2,
      name: { ko: '부산 중앙M리츠B', en: 'Busan Jungang M REITs B' },
      principal: 9700000,
      operatingProfit: 0,
      contractDate: '2019.04.15',
      evalMethod: { ko: '시가', en: 'Market Value' },
      afterTaxProfit: 0,
      maturityDate: '2024.07.31',
      trustFee: 0,
      tax: 0,
      settlementCurrency: { ko: 'KRW', en: 'KRW' },
    },
    {
      seqNo: 3,
      name: { ko: '부산 중앙M리츠A', en: 'Busan Jungang M REITs A' },
      principal: 29100000,
      operatingProfit: 0,
      contractDate: '2019.04.15',
      evalMethod: { ko: '시가', en: 'Market Value' },
      afterTaxProfit: 0,
      maturityDate: '2024.07.31',
      trustFee: 0,
      tax: 0,
      settlementCurrency: { ko: 'KRW', en: 'KRW' },
    },
  ],
  principalSum: 87300000,
  trustFeeSum: 0,
  taxSum: 0,
  operatingProfitSum: 0,
  afterTaxSum: 0,
  assets: [
    { seqNo: 1, fundName: { ko: '부산 중앙M리츠B', en: 'Busan Jungang M REITs B' }, assetDivision: { ko: '부동산', en: 'Real Estate' }, securityName: { ko: '엠프라퍼티제1호위탁', en: 'M Property No.1 Trust' }, buyAmount: 48500000, evalAmount: 48500000, buyReturn: 0, marketReturn: 0, creditRating: { ko: '해당없음', en: 'N/A' } },
    { seqNo: 2, fundName: { ko: '부산 중앙M리츠B', en: 'Busan Jungang M REITs B' }, assetDivision: { ko: '부동산', en: 'Real Estate' }, securityName: { ko: '엠프라퍼티제1호위탁', en: 'M Property No.1 Trust' }, buyAmount: 9700000, evalAmount: 9700000, buyReturn: 0, marketReturn: 0, creditRating: { ko: '해당없음', en: 'N/A' } },
    { seqNo: 3, fundName: { ko: '부산 중앙M리츠A', en: 'Busan Jungang M REITs A' }, assetDivision: { ko: '부동산', en: 'Real Estate' }, securityName: { ko: '엠프라퍼티제1호위탁', en: 'M Property No.1 Trust' }, buyAmount: 29100000, evalAmount: 29100000, buyReturn: 0, marketReturn: 0, creditRating: { ko: '해당없음', en: 'N/A' } },
  ],
};
