// 실제 고객 데이터가 아닌, 화면 구조를 보여주기 위한 예시(더미) 데이터입니다.

export const text = {
  screenName: { ko: '금융소득 원천징수 명세서', en: 'Financial Income Withholding Tax Statement' },
  fiscalYear: { ko: '귀속연도 : ', en: 'Fiscal Year: ' },
  fiscalYearSuffix: { ko: '년', en: '' },
  name: { ko: '성명', en: 'Name' },
  residentNo: { ko: '주민등록번호', en: 'Resident Registration No.' },
  totalPrefix: { ko: '총 ', en: 'Total: ' },
  totalSuffix: { ko: '건', en: ' items' },
  unitWon: { ko: '(단위:원)', en: '(Unit: KRW)' },
  col: {
    accountNo: { ko: '계좌번호', en: 'Account Number' },
    incomeType: { ko: '소득종류', en: 'Income Type' },
    incomeAmount: { ko: '소득금액(세전금액)', en: 'Income Amount (Pre-Tax)' },
    taxDivision: { ko: '과세구분', en: 'Tax Division' },
    incomeTax: { ko: '소득세', en: 'Income Tax' },
    localTax: { ko: '지방소득세', en: 'Local Income Tax' },
    total: { ko: '합계', en: 'Total' },
    details: { ko: '상세보기', en: 'Details' },
  },
  noResult: { ko: '내역이 없습니다', en: 'No records found.' },
  detail: {
    accountNo: { ko: '계좌번호', en: 'Account Number' },
    withholdingAgent: { ko: '원천징수의무자', en: 'Withholding Agent' },
    branchName: { ko: '점포명', en: 'Branch Name' },
    businessNo: { ko: '사업자등록번호', en: 'Business Registration No.' },
    incomeType: { ko: '소득종류', en: 'Income Type' },
    incomeAmount: { ko: '소득금액(세전금액)', en: 'Income Amount (Pre-Tax)' },
    taxDivision: { ko: '과세구분', en: 'Tax Division' },
    withholdingTax: { ko: '원천징수세액', en: 'Withholding Tax' },
    incomeTax: { ko: '소득세', en: 'Income Tax' },
    localTax: { ko: '지방소득세', en: 'Local Income Tax' },
    total: { ko: '합계', en: 'Total' },
  },
  close: { ko: '닫기', en: 'Close' },
  sumTit: { ko: '금융소득 및 원천징수세액 합계', en: 'Financial Income and Withholding Tax Total' },
  sumCol: {
    division: { ko: '구분', en: 'Category' },
    incomeAmount: { ko: '소득금액(세전금액)', en: 'Income Amount (Pre-Tax)' },
    incomeTax: { ko: '소득세', en: 'Income Tax' },
    localTax: { ko: '지방소득세', en: 'Local Income Tax' },
    taxSum: { ko: '세액계', en: 'Total Tax' },
  },
  sumRows: [
    { ko: '비과세(E)', en: 'Tax-Exempt (E)' },
    { ko: '분리과세(L,H,R,O,B)', en: 'Separate Taxation (L,H,R,O,B)' },
    { ko: '종합과세이자·배당소득(T)', en: 'Comprehensive Interest/Dividend Income (T)' },
    { ko: 'Gross-up 대상 배당소득(D,G)', en: 'Gross-up Dividend Income (D,G)' },
    { ko: '종합과세대상 금액(③ + ④)', en: 'Comprehensive Taxation Amount (③ + ④)' },
  ],
  sumNotes: [
    { ko: '소득자의 주민등록번호 뒷자리 및 계좌번호 뒷자리는 개인정보보호를 위해 ***** 처리하였습니다.', en: 'The last digits of the resident registration number and account number are masked (*****) for privacy protection.' },
    { ko: '소득금액은 계좌별 연간 합계금액으로 작성하였습니다.', en: 'Income amounts are the annual total per account.' },
    {
      ko: '종합과세 대상에서 제외되는 비과세 · 분리과세소득(세금우대저축 등)을 기재하여 통보하나, 종합과세 대상은 아닙니다.',
      en: 'Tax-exempt/separately-taxed income (such as tax-preferred savings) excluded from comprehensive taxation is shown but is not subject to comprehensive taxation.',
      sub: [
        { ko: '각 금융회사에서 발생하는 비과세 · 분리과세소득을 제외한 금융소득 중 종합과세 대상금액이 2천만원을 초과하는 경우에는 종합소득세 신고 대상입니다.', en: 'If comprehensive-taxation financial income (excluding tax-exempt/separately-taxed income) from all financial institutions exceeds 20 million KRW, comprehensive income tax filing is required.' },
      ],
    },
    { ko: '금융소득이 2천만원 이하인 경우에도 소득세법 제127조에 의해 원천징수되지 아니한 이자 · 배당소득이 있는 경우 종합소득세 확정신고를 하셔야 합니다.', en: 'Even if financial income is 20 million KRW or less, if there is interest/dividend income not withheld under Article 127 of the Income Tax Act, comprehensive income tax filing is required.' },
    {
      ko: '과세구분',
      en: 'Tax Division',
      sub: [
        { ko: '비과세(면제) : (E)', en: 'Tax-exempt: (E)' },
        { ko: '분리과세 : 14%미만 저율(L), 14%초과 고율(H), 비실명(R), 일반세율(O), 기본세율(B)', en: 'Separate taxation: below 14% (L), above 14% (H), unnamed (R), general rate (O), basic rate (B)' },
        { ko: '종합과세 : Gross-up 대상 배당소득(D,G), 위 이외의 일반이자 · 배당소득(T)', en: 'Comprehensive taxation: Gross-up dividend income (D,G), other general interest/dividend income (T)' },
      ],
    },
    { ko: '기타 문의사항은 거래하시는 영업점 또는 당사 고객지원센터(1588-0365)로 문의하시기 바랍니다.', en: 'For other inquiries, please contact your branch or our Customer Center (1588-0365).' },
  ],
  companyName: { ko: '신한투자증권 주식회사', en: 'Shinhan Investment Corp.' },
  guideTit: { ko: '안내사항', en: 'Notice' },
  guideItems: [
    { ko: '이 명세서는 소득세법에 따라 작성 · 교부하여 드리는 것이며, 전 금융기관을 통해 종합과세 대상 금융소득(이자 · 배당소득)의 연간 합계금액이 개인별로 2천만원을 초과하는 경우에는 5월 중에 본인 주소지 관할세무서(또는 홈택스)에 종합소득세를 신고 · 납부하셔야 합니다.', en: 'This statement is prepared under the Income Tax Act; if your total comprehensive-taxation financial income across all institutions exceeds 20 million KRW annually, you must file and pay comprehensive income tax in May at your local tax office (or Hometax).' },
    { ko: '당사는 \'소득세법 제164조 [지급명세서의 제출]\'에 따라 고객의 금융소득 내용(파기계좌 포함)을 국세청에 제공하고 있습니다.', en: 'Per Article 164 of the Income Tax Act (Submission of Payment Statements), we provide customer financial income details (including closed accounts) to the National Tax Service.' },
  ],
};

export const sampleData = {
  fiscalYear: '2024',
  name: { ko: '류원희', en: 'Wonhee Ryu' },
  residentNo: '900101',
  incomes: [
    {
      accountNo: '20385174602',
      businessNo: '104-81-15029',
      branchName: { ko: '강남금융센터', en: 'Gangnam Finance Center' },
      incomeType: { ko: '배당소득', en: 'Dividend Income' },
      incomeAmount: 156000,
      taxDivision: { ko: '일반과세(T)', en: 'General Taxation (T)' },
      incomeTax: 21840,
      localTax: 2184,
      total: 24024,
    },
    {
      accountNo: '20385174602',
      businessNo: '104-81-15029',
      branchName: { ko: '강남금융센터', en: 'Gangnam Finance Center' },
      incomeType: { ko: '이자소득', en: 'Interest Income' },
      incomeAmount: 38000,
      taxDivision: { ko: '일반과세(T)', en: 'General Taxation (T)' },
      incomeTax: 5320,
      localTax: 532,
      total: 5852,
    },
  ],
  summary: [
    { incomeAmount: 0, incomeTax: 0, localTax: 0, taxSum: 0 },
    { incomeAmount: 0, incomeTax: 0, localTax: 0, taxSum: 0 },
    { incomeAmount: 194000, incomeTax: 27160, localTax: 2716, taxSum: 29876 },
    { incomeAmount: 0, incomeTax: 0, localTax: 0, taxSum: 0 },
    { incomeAmount: 194000, incomeTax: 27160, localTax: 2716, taxSum: 29876 },
  ],
  signDate: { ko: '2025년 01월 15일', en: 'Jan 15, 2025' },
};
