// 실제 고객 데이터가 아닌, 화면 구조를 보여주기 위한 예시(더미) 데이터입니다.
// 금액/수량은 실제 계좌를 특정할 수 없도록 임의로 무작위 생성했습니다.

export const text = {
  screenName: { ko: '일임형 종합자산관리계좌 성과보고서', en: 'Discretionary Wrap Account Performance Report' },
  baseDateLabel: { ko: '작성기준일 : ', en: 'Prepared as of: ' },
  summaryTit: { ko: '수익률 요약서', en: 'Return Summary' },
  basicInfoTit: { ko: '기본정보', en: 'Basic Information' },
  contractor: { ko: '계약자명', en: 'Contractor' },
  productName: { ko: '상품명', en: 'Product Name' },
  accountNo: { ko: '계좌번호', en: 'Account Number' },
  firstContractDate: { ko: '최초계약일', en: 'Initial Contract Date' },
  investPeriod: { ko: '투자기간', en: 'Investment Period' },
  days: { ko: '일', en: ' days' },
  infoBaseDate: { ko: '정보제공 기준시점', en: 'Information Reference Date' },
  keyInfoTit: { ko: '주요정보', en: 'Key Information' },
  keyInfoText1: { ko: ' 기준으로 고객님과 체결한 투자일임계약의 평가금액은 ', en: ', the valuation amount of the discretionary investment contract concluded with you is ' },
  keyInfoText2: { ko: ' 원, 누적수익률은 ', en: ', and the cumulative return is ' },
  keyInfoText3: { ko: ' % 입니다.', en: '%.' },
  principal: { ko: '투자원금', en: 'Investment Principal' },
  withdrawal: { ko: '중도인출대금', en: 'Interim Withdrawal' },
  fees: { ko: '수수료, 보수', en: 'Fees & Commissions' },
  toggleExplain: {
    ko: '총 투자 원금 ({p} 원)에서 중도인출대금 ({w} 원) 및 수수료, 보수 ({f} 원)를 차감한 금액을 투자일임업자가 운용한 결과가 평가금액 ({v} 원)입니다.',
    en: 'The amount remaining after subtracting the interim withdrawal ({w} KRW) and fees/commissions ({f} KRW) from the total investment principal ({p} KRW), as managed by the discretionary investment manager, results in the valuation amount ({v} KRW).',
  },
  valuation: { ko: '평가금액', en: 'Valuation Amount' },
  cumulativeReturn: { ko: '누적수익률', en: 'Cumulative Return' },
  annualizedReturn: { ko: '연환산수익률', en: 'Annualized Return' },
  terminationExplain: {
    ko: '참고로 정보제공 기준시점의 중도해지를 가정시 평가금액({v} 원)에서 중도해지수수료등을 차감 후 예상되는 가액이 해지예상금액 ({e} 원)입니다.',
    en: 'For reference, assuming early termination as of the information reference date, the expected value after deducting early termination fees from the valuation amount ({v} KRW) is the estimated termination amount ({e} KRW).',
  },
  expectedTermination: { ko: '해지예상금액', en: 'Estimated Termination Amount' },
  deductionExpected: { ko: '차감예상액', en: 'Expected Deduction' },
  deductionExpectedSub: { ko: '(해지수수료, 세금 등)', en: '(Termination fee, tax, etc.)' },
  referenceTit: { ko: '참고사항', en: 'Reference Notes' },
  referenceNotes: [
    { ko: '해당 해지예상금액은 청산(매도)해지를 가정한 금액이며 상품에 따라 청산(매도)해지가 불가능할 수도 있습니다.', en: 'The estimated termination amount assumes liquidation (sale) termination; liquidation termination may not be possible depending on the product.' },
    { ko: '실제 세금은 기타 사실관계에 따라 다른 결과가 나올 수 있으므로 모든 예상액은 실제 해지 후와 차이가 발생할 수 있으니 참고바랍니다.', en: 'Actual taxes may differ depending on other facts, so all estimated amounts may differ from the actual amount after termination.' },
    { ko: '채권 평가금액으로 계산되는 단가는 변동될 수 있습니다.', en: 'The unit price used to calculate bond valuation amounts may change.' },
    {
      ko: '아래 자산의 경우 수수료와 세금차감이 되지 않은 금액이 해지예상금액으로 계산됩니다.',
      en: 'For the assets below, the estimated termination amount is calculated before deducting fees and taxes.',
      sub: { ko: '(CD, KOSPI선물, KOSPI옵션, 해외증권, 외화, 해외채권, 신탁, 금현물, 발행어음, 외화 RP, KOFEX선물, KPREX 옵션 등)', en: '(CD, KOSPI Futures, KOSPI Options, Overseas Securities, Foreign Currency, Overseas Bonds, Trusts, Physical Gold, Promissory Notes, Foreign Currency RP, KOFEX Futures, KPREX Options, etc.)' },
    },
    { ko: '세제혜택이 있는 랩상품의 경우 실제 해지예상금액은 해지시점에 따라 변동될 수 있습니다.', en: 'For wrap products with tax benefits, the actual estimated termination amount may vary depending on the time of termination.' },
    { ko: '시장성 없는 자산 등 일부 자산은 해지예상금액에서 제외될 수 있습니다.', en: 'Some assets, such as non-marketable assets, may be excluded from the estimated termination amount.' },
    { ko: '수익률 계산방식의 차이에 따라 수익률요약서와 성과보고서의 수익률차이가 발생할 수 있습니다.', en: 'Differences in return calculation methods may cause discrepancies between the return summary and the performance report.',
      circleItems: [
        { ko: '수익률요약서 누적수익률 : (평가금액+중도인출대금)/투자원금-1', en: 'Return Summary cumulative return: (Valuation + Interim Withdrawal) / Principal − 1' },
        { ko: '성과보고서 누적시간가중수익률, 분기시간가중수익률', en: 'Performance Report cumulative & quarterly time-weighted return' },
      ] },
    { ko: '랩계좌 입출금 여부에 따라 수익률요약서의 투자원금과 성과보고서의 계약금액이 상이할 수 있습니다.', en: 'The investment principal in the Return Summary and the contract amount in the Performance Report may differ depending on wrap account deposits/withdrawals.',
      circleItems: [
        { ko: '"투자원금"은 투자일임계좌에 납입(입금)한 금액의 누계입니다.', en: '"Investment Principal" is the cumulative amount deposited into the discretionary investment account.' },
        { ko: '"중도인출대금"은 투자기간 중 랩계좌에서 인출(출금)한 금액의 누계입니다. 고객 위탁계좌에서 실제 입출금이 없더라도 동일 계좌 내의 상품간(위탁↔EMA등 랩계좌) 예수금 전환(이동)시 입금/출금 으로 인식됩니다.', en: '"Interim Withdrawal" is the cumulative amount withdrawn from the wrap account during the investment period, including internal transfers between products within the same account.' },
      ] },
    { ko: '시간가중수익률 : 투자가 시작되는 시점부터 현금흐름이 발생한 시점까지를 하나의 기간으로 간주하여 계산한 수익률을 전체 투자기간에 대한 수익률로 환산하여 표시',
      en: 'Time-weighted return: the return calculated by treating each period between cash flow events as a single period, converted to a return over the entire investment period.',
      formula: [
        { ko: 'T일 수익률 : (당일 평가액 - 전일 평가액 - 현금유출액) / 전일평가액', en: 'Day T return: (Day T valuation − Day T-1 valuation − cash outflow) / Day T-1 valuation' },
        { ko: 'T+1일 수익률 : (T+1일 평가액 - T일 평가액 - T+1일 현금유출액) / T일 평가액', en: 'Day T+1 return: (Day T+1 valuation − Day T valuation − Day T+1 cash outflow) / Day T valuation' },
        { ko: 'T+1일 누적수익률 : {1+(T일 수익률)} X {1+(T+1일 수익률)} -1', en: 'Day T+1 cumulative return: {1+(Day T return)} × {1+(Day T+1 return)} − 1' },
      ] },
  ],
  reportSectionTit: { ko: '일임형 종합자산관리계좌 성과보고서', en: 'Discretionary Wrap Account Performance Report' },
  contractAmount: { ko: '계약금액', en: 'Contract Amount' },
  cumulativeProfit: { ko: '누적 수익금', en: 'Cumulative Profit' },
  cumulativeReturnPeriod: { ko: '누적 수익률', en: 'Cumulative Return' },
  quarterlyProfit: { ko: '분기 수익금', en: 'Quarterly Profit' },
  quarterlyReturnPeriod: { ko: '분기 수익률', en: 'Quarterly Return' },
  returnNote: { ko: '상기 수익률은 시간가중수익률로 제반 비용 및 수수료 차감 전 수익이며, 수익률 요약서상의 누적수익률과 다를 수 있습니다.', en: 'The above return is a time-weighted return before deducting fees and expenses, and may differ from the cumulative return shown in the Return Summary.' },
  s1Tit: { ko: '1. 투자일임계약의 개요', en: '1. Overview of the Discretionary Investment Contract' },
  wrapService: { ko: 'Wrap서비스', en: 'Wrap Service' },
  accountName: { ko: '계좌명', en: 'Account Name' },
  riskProfile: { ko: '투자성향/상품위험등급', en: 'Risk Profile / Product Risk Grade' },
  serviceRegDate: { ko: '서비스등록일', en: 'Service Registration Date' },
  contractPeriod: { ko: '계약기간', en: 'Contract Period' },
  overseasInvest: { ko: '해외투자여부', en: 'Overseas Investment' },
  benchmark: { ko: '벤치마크', en: 'Benchmark' },
  expectedMaturity: { ko: '예상만기일', en: 'Expected Maturity Date' },
  wrapBranch: { ko: 'Wrap관리점', en: 'Wrap Managing Branch' },
  wrapManager: { ko: 'Wrap관리자', en: 'Wrap Manager' },
  managingFirm: { ko: '담당운용처', en: 'Managing Firm' },
  managingAgent: { ko: '담당운용역', en: 'Managing Agent' },
  investTendency: { ko: '투자성향', en: 'Investment Tendency' },
  restriction: { ko: '운용 제한사항', en: 'Management Restrictions' },
  s1Note1: { ko: '상기 계약기간은 약관상의 랩서비스 기본계약기간이며, 해당 랩서비스의 투자기간은 각 핵심설명서를 참고하시기 바랍니다.', en: 'The above contract period is the basic contract period of the wrap service under the terms; please refer to the key product description for the actual investment period.' },
  s1Note2: { ko: '예상만기일은 랩서비스 내 만기형 사모펀드가 편입되어 있는 경우 편입자산의 예상만기를 나타내는 것으로 편입자산의 환매가능여부에 따라 변동될 수 있습니다.', en: 'The expected maturity date represents the expected maturity of the underlying assets when a maturity-type private fund is included in the wrap service, and may vary depending on redeemability.' },
  s2Tit: { ko: '2. 투자일임재산 운용실적', en: '2. Investment Management Performance' },
  s2aTit: { ko: '가. 기간 수익률 및 수익률 추이', en: 'a. Period Returns and Return Trend' },
  unitPercent: { ko: '(단위:%)', en: '(Unit: %)' },
  col: {
    division: { ko: '구분', en: 'Category' },
    m3: { ko: '최근3개월', en: '3 Months' },
    m6: { ko: '최근6개월', en: '6 Months' },
    m9: { ko: '최근9개월', en: '9 Months' },
    m12: { ko: '최근12개월', en: '12 Months' },
    cumulative: { ko: '누적수익률', en: 'Cumulative' },
  },
  cumulativeLineTit: { ko: '누적 수익률 그래프', en: 'Cumulative Return Chart' },
  s2bTit: { ko: '나. 수익률 구성', en: 'b. Return Composition' },
  legendCurrent: { ko: '(당분기말 비중)', en: '(Current Quarter Weight)' },
  legendPrior: { ko: '(전분기말 비중)', en: '(Prior Quarter Weight)' },
  note1: { ko: '주1) 수익률은 해당기간(분기) 수익률', en: 'Note 1) Return is the return for the period (quarter).' },
  col2: {
    assetClass: { ko: '자산군', en: 'Asset Class' },
    returnRate: { ko: '수익률', en: 'Return' },
    holdingStatus: { ko: '자산보유현황', en: 'Holding Status' },
    weight: { ko: '비중', en: 'Weight' },
    weightSub: { ko: '비중', en: 'Weight' },
    cumulativeReturnSub: { ko: '누적 수익률', en: 'Cumulative Return' },
  },
  recent3mLineTit: { ko: '최근 3개월 그래프', en: 'Recent 3-Month Chart' },
  s3Tit: { ko: '3. 투자일임재산 자산구성현황', en: '3. Asset Composition Status' },
  s3aTit: { ko: '가. 자산 유형별 현황', en: 'a. Status by Asset Type' },
  unitWonPercent: { ko: '(단위:원, %)', en: '(Unit: KRW, %)' },
  evalAmount: { ko: '평가금액', en: 'Valuation' },
  weight: { ko: '비중', en: 'Weight' },
  total: { ko: '합계', en: 'Total' },
  assetTypeWeightTit: { ko: '자산 유형별 비중', en: 'Weight by Asset Type' },
  s3bTit: { ko: '나. 자산 종류별 현황', en: 'b. Status by Asset Category' },
  securityWeightTit: { ko: '유가 증권별 비중', en: 'Weight by Security' },
  s3cTit: { ko: '다. 자산 종목 보유 현황', en: 'c. Asset Holdings Status' },
  unitWonSharesPercent: { ko: '(단위:원, 주, 좌, %)', en: '(Unit: KRW, shares, units, %)' },
  col3: {
    division: { ko: '구분', en: 'Category' },
    securityName: { ko: '종목명', en: 'Security Name' },
    baseCurrency: { ko: '기준통화', en: 'Base Currency' },
    holdingQty: { ko: '보유수량', en: 'Qty Held' },
    returnRate: { ko: '수익률', en: 'Return' },
    region: { ko: '지역', en: 'Region' },
    avgPrice: { ko: '평균단가', en: 'Avg. Price' },
    currentPrice: { ko: '현재가(기준가)', en: 'Current Price (NAV)' },
  },
  s4Tit: { ko: '4. 운용 현황', en: '4. Management Status' },
  s5Tit: { ko: '5. 운용 계획', en: '5. Management Plan' },
  s6Tit: { ko: '6. 매매 내역', en: '6. Trading History' },
  s6aTit: { ko: '가. 유가증권 매매 내역', en: 'a. Securities Trading History' },
  unitWonSharesUnits: { ko: '(단위:원, 주, 좌)', en: '(Unit: KRW, shares, units)' },
  col4: {
    division: { ko: '구분', en: 'Category' },
    securityName: { ko: '종목명', en: 'Security Name' },
    qty: { ko: '수량', en: 'Qty' },
    tradeAmount: { ko: '매매금액', en: 'Trade Amount' },
    tradeDate: { ko: '매매일자', en: 'Trade Date' },
    tradePrice: { ko: '매매단가', en: 'Trade Price' },
    tradeFee: { ko: '매매수수료', en: 'Trade Fee' },
    taxes: { ko: '각종세금', en: 'Taxes' },
  },
  s6bTit: { ko: '나. 유동성(MMW) 운용결과', en: 'b. Liquidity (MMW) Management Results' },
  unitWon: { ko: '(단위:원)', en: '(Unit: KRW)' },
  col5: {
    period: { ko: '기간', en: 'Period' },
    totalInvested: { ko: '총투자금액', en: 'Total Invested' },
    totalRedeemed: { ko: '총상환금액', en: 'Total Redeemed' },
    profitLoss: { ko: '투자손익', en: 'Profit/Loss' },
  },
  mmwNote1: { ko: 'MMW상품은 일일 재투자 방식으로 상기의 총투자금액은 영업일 기준 MMW예치금액의 총합계액입니다.', en: 'MMW products reinvest daily, so the total invested amount above is the sum of MMW deposits on a business-day basis.', sub: { ko: '(ex. 한달(영업일기준 25일)동안 100만원을 예치하였을 경우 총 투자금액은 2500만원이 됨)', en: '(e.g., depositing 1,000,000 KRW for one month (25 business days) results in a total invested amount of 25,000,000 KRW)' } },
  mmwNote2: { ko: '상기금액은 수수료, 세금이 반영된 금액입니다.', en: 'The above amount reflects fees and taxes.' },
  s7Tit: { ko: '7. 매매 회전율', en: '7. Trading Turnover' },
  buyAmount: { ko: '매수금액', en: 'Buy Amount' },
  sellAmount: { ko: '매도금액', en: 'Sell Amount' },
  turnoverTit: { ko: '매매회전율', en: 'Trading Turnover' },
  currentPeriod: { ko: '해당기간', en: 'Current Period' },
  cumulativePeriod: { ko: '누적기간', en: 'Cumulative Period' },
  turnoverFormula: { ko: '매매회전율 = [(매수금액+매도금액) ÷ 2/(투자일임계약의 전체 일평균가금액)]X100', en: 'Turnover = [(Buy + Sell) ÷ 2 / (Average Daily Contract Value)] × 100' },
  s8Tit: { ko: '8. 계좌입출금 정보', en: '8. Account Deposit/Withdrawal Information' },
  col6: {
    period: { ko: '기간 입금 금액', en: 'Period Deposit' },
    withdrawal: { ko: '기간 출금 금액', en: 'Period Withdrawal' },
    balance: { ko: '출입금 잔액', en: 'Deposit/Withdrawal Balance' },
  },
  s9Tit: { ko: '9. 권리사항', en: '9. Rights Information' },
  col7: {
    division: { ko: '구분', en: 'Category' },
    securityName: { ko: '종목명', en: 'Security Name' },
    detailDivision: { ko: '세부구분', en: 'Sub-Category' },
    rightQty: { ko: '권리발생수량', en: 'Rights Qty' },
    amount: { ko: '금액', en: 'Amount' },
    rightDetails: { ko: '권리사항', en: 'Right Details' },
    baseRate: { ko: '기준환율', en: 'Base FX Rate' },
    taxes: { ko: '제세금', en: 'Taxes' },
  },
  s10Tit: { ko: '투자위험 노출 상황 및 기타 안내 사항', en: 'Investment Risk Exposure and Other Notices' },
  s11Tit: { ko: '11. 고유재산과의 거래 여부', en: '11. Transactions with Proprietary Assets' },
  s11Text: { ko: '해당 사항 없음', en: 'Not applicable' },
  s12Tit: { ko: '12. 투자자문회사에 대한 사항', en: '12. Investment Advisory Firm Details' },
  s13Tit: { ko: '13. 수수료 징수 내역', en: '13. Fee Collection Details' },
  period: { ko: '해당기간', en: 'Period' },
  discretionaryFee: { ko: '투자일임수수료', en: 'Discretionary Management Fee' },
  performanceFee: { ko: '성과보수', en: 'Performance Fee' },
  otherTradeCost: { ko: '기타매매비용', en: 'Other Trading Costs' },
  taxes: { ko: '각종세금', en: 'Taxes' },
  otherCost: { ko: '기타비용', en: 'Other Costs' },
  totalCost: { ko: '총비용', en: 'Total Cost' },
  s14Tit: { ko: '14. 랩수수료 부과기준 및 방법', en: '14. Wrap Fee Basis and Method' },
  s15Tit: { ko: '15. 성과보수 부과기준 및 방법', en: '15. Performance Fee Basis and Method' },
  s16Tit: { ko: '16. 투자운용전문인력 현황', en: '16. Investment Management Personnel Status' },
  position: { ko: '직위', en: 'Position' },
  name: { ko: '성명', en: 'Name' },
  mgmtStartDate: { ko: '운용개시일', en: 'Management Start Date' },
  otherContracts: { ko: '운용중인 다른 투자일임계약 현황', en: 'Other Discretionary Contracts Managed' },
  contractCount: { ko: '투자일임계약', en: 'Discretionary Contracts' },
  contractCountUnit: { ko: ' 건', en: '' },
  scale: { ko: '운용규모', en: 'AUM' },
  scaleUnit: { ko: ' 백만원', en: ' million KRW' },
  career: { ko: '주요경력', en: 'Key Career' },
  contact: { ko: '연락처', en: 'Contact' },
  s17Tit: { ko: '17. 투자권유자 정보', en: '17. Investment Recommender Information' },
  recommenderInfo: { ko: '투자권유자 정보', en: 'Recommender Information' },
  s17Note: { ko: '고객님의 투자목적, 투자경험, 위험선호의 정도 및 투자예정기간 등에 변경사항이 있을 경우, 담당일임자산운용사와 상담을 통하여 투자일임방법을 변경하시기 바랍니다.', en: 'If there are any changes to your investment objectives, experience, risk tolerance, or intended investment period, please consult your discretionary asset manager to update your investment management method.' },
  companyName: { ko: '신한투자증권주식회사', en: 'Shinhan Investment Corp.' },
};

export const sampleData = {
  baseDate: '2024-06-18',
  contractor: { ko: '류원희', en: 'Wonhee Ryu' },
  productName: { ko: '신한 마이더스 알파 랩', en: 'Shinhan Midas Alpha Wrap' },
  accountNo: '20583917462',
  firstContractDate: '2022.06.18',
  investPeriod: 732,
  infoBaseDate: '2024.06.18',
  principal: 50000000,
  withdrawal: 0,
  fees: 386420,
  valuation: 54862300,
  cumulativeReturn: 9.72,
  annualizedReturn: 4.85,
  terminationDeduction: 120000,
  expectedTermination: 54742300,
  contractAmount: 50000000,
  reportValuation: 54862300,
  cumulativeProfit: 4862300,
  cumulativeReturnFrom: '22년06월18일',
  cumulativeReturnTo: '24년06월18일',
  cumulativeReturnPct: 9.72,
  quarterlyProfit: 683200,
  quarterlyReturnFrom: '24년03월18일',
  quarterlyReturnTo: '24년06월18일',
  quarterlyReturnPct: 1.26,
  wrapService: { ko: '신한 마이더스 알파 랩', en: 'Shinhan Midas Alpha Wrap' },
  accountName: { ko: '류원희', en: 'Wonhee Ryu' },
  riskTendency: { ko: '적극투자형', en: 'Aggressive' },
  riskGrade: { ko: '2등급', en: 'Grade 2' },
  serviceRegDate: '2022.06.18',
  contractFrom: '2022.06.18',
  contractTo: '2025.06.18',
  overseasInvest: { ko: '해당없음', en: 'N/A' },
  benchmark: { ko: 'KOSPI 200', en: 'KOSPI 200' },
  expectedMaturity: '2025.06.18',
  wrapBranch: { ko: '강남금융센터', en: 'Gangnam Finance Center' },
  wrapManager: { ko: '김지수', en: 'Jisoo Kim' },
  managingFirm: { ko: '신한자산운용', en: 'Shinhan Asset Management' },
  managingAgent: { ko: '카리나', en: 'Karina' },
  investTendency: { ko: '적극투자형', en: 'Aggressive' },
  restriction: { ko: '해당없음', en: 'None' },
  periodReturns: [
    { division: { ko: '수익률(%)', en: 'Return (%)' }, m3: 2.14, m6: 3.85, m9: 6.02, m12: 8.41, cumulative: 9.72 },
  ],
  cumulativeLine: [
    { date: '23.06', value: 1.2 }, { date: '23.09', value: 3.4 }, { date: '23.12', value: 5.1 },
    { date: '24.03', value: 7.9 }, { date: '24.06', value: 9.72 },
  ],
  recent3mLine: [
    { date: '04.01', value: 0.3 }, { date: '04.15', value: -0.5 }, { date: '05.01', value: 0.8 },
    { date: '05.15', value: 1.4 }, { date: '06.01', value: 1.1 }, { date: '06.18', value: 1.26 },
  ],
  returnComposition: [
    { assetClass: { ko: '국내주식', en: 'Domestic Equity' }, priorReturn: 1.1, currentReturn: 1.4, cumulativeReturn: 8.2, holding: { ko: '보유중', en: 'Held' }, currentWeight: 45, priorWeight: 40 },
    { assetClass: { ko: '국내채권', en: 'Domestic Bond' }, priorReturn: 0.5, currentReturn: 0.6, cumulativeReturn: 3.1, holding: { ko: '보유중', en: 'Held' }, currentWeight: 35, priorWeight: 38 },
    { assetClass: { ko: '유동성', en: 'Liquidity' }, priorReturn: 0.1, currentReturn: 0.1, cumulativeReturn: 0.6, holding: { ko: '보유중', en: 'Held' }, currentWeight: 20, priorWeight: 22 },
  ],
  assetTypeHeaderCurrent: { ko: '당분기말', en: 'Current Quarter' },
  assetTypeHeaderPrior: { ko: '전분기말', en: 'Prior Quarter' },
  assetTypeRows: [
    { name: { ko: '국내주식', en: 'Domestic Equity' }, currentAmount: 24688035, currentWeight: 45.0, priorAmount: 20450000, priorWeight: 40.0 },
    { name: { ko: '국내채권', en: 'Domestic Bond' }, currentAmount: 19201805, currentWeight: 35.0, priorAmount: 19450000, priorWeight: 38.0 },
    { name: { ko: '유동성', en: 'Liquidity' }, currentAmount: 10972460, currentWeight: 20.0, priorAmount: 11250000, priorWeight: 22.0 },
  ],
  assetTypeSum: { name: { ko: '합계', en: 'Total' }, currentAmount: 54862300, currentWeight: 100.0, priorAmount: 51150000, priorWeight: 100.0 },
  securityHeaderCurrent: { ko: '당분기말', en: 'Current Quarter' },
  securityHeaderPrior: { ko: '전분기말', en: 'Prior Quarter' },
  securityRows: [
    { name: { ko: '삼성전자', en: 'Samsung Electronics' }, currentAmount: 14688035, currentWeight: 26.8, priorAmount: 12450000, priorWeight: 24.3 },
    { name: { ko: '국고채 10년', en: 'KTB 10Y' }, currentAmount: 19201805, currentWeight: 35.0, priorAmount: 19450000, priorWeight: 38.0 },
    { name: { ko: 'MMW', en: 'MMW' }, currentAmount: 10972460, currentWeight: 20.0, priorAmount: 11250000, priorWeight: 22.0 },
    { name: { ko: '기타', en: 'Other' }, currentAmount: 10000000, currentWeight: 18.2, priorAmount: 8000000, priorWeight: 15.7 },
  ],
  holdings: [
    { division: { ko: '주식', en: 'Equity' }, name: { ko: '삼성전자', en: 'Samsung Electronics' }, currency: { ko: 'KRW', en: 'KRW' }, region: { ko: '국내', en: 'Domestic' }, qty: 180, avgPrice: 68500, currentPrice: 81600, returnRate: 19.12 },
    { division: { ko: '채권', en: 'Bond' }, name: { ko: '국고채 10년', en: 'KTB 10Y' }, currency: { ko: 'KRW', en: 'KRW' }, region: { ko: '국내', en: 'Domestic' }, qty: 20000000, avgPrice: 9820, currentPrice: 9910, returnRate: 0.92 },
  ],
  managementStatus: {
    ko: '분기 중 국내 증시 변동성 확대에 대응하여 우량 대형주 비중을 유지하며 채권 듀레이션을 단기화하였습니다.',
    en: 'In response to increased domestic market volatility this quarter, we maintained our weighting in quality large-cap stocks and shortened bond duration.',
  },
  managementPlan: {
    ko: '다음 분기에는 금리 인하 기대감을 반영하여 채권 비중을 점진적으로 확대할 계획입니다.',
    en: 'Next quarter, we plan to gradually increase our bond allocation in anticipation of rate cuts.',
  },
  trades: [
    { division: { ko: '매수', en: 'Buy' }, name: { ko: '삼성전자', en: 'Samsung Electronics' }, date: '2024-05-02', qty: 30, price: 75200, amount: 2256000, fee: 338, tax: 0 },
    { division: { ko: '매도', en: 'Sell' }, name: { ko: 'SK하이닉스', en: 'SK Hynix' }, date: '2024-05-20', qty: 10, price: 189500, amount: 1895000, fee: 284, tax: 5116 },
  ],
  mmw: [
    { from: '2024.03.18', to: '2024.06.18', totalInvested: 273500000, totalRedeemed: 272800000, profitLoss: 46500 },
  ],
  buyAmount: 18420000,
  sellAmount: 17650000,
  turnoverCurrent: 12.4,
  turnoverCurrentFrom: '2024.03.18',
  turnoverCurrentTo: '2024.06.18',
  turnoverCumulative: 48.2,
  turnoverCumulativeFrom: '2022.06.18',
  turnoverCumulativeTo: '2024.06.18',
  deposits: [
    { month: '2024.06', deposit: 0, withdrawal: 0, balance: 0 },
  ],
  rights: [
    { division: { ko: '배당', en: 'Dividend' }, name: { ko: '삼성전자', en: 'Samsung Electronics' }, detailDivision: { ko: '현금배당', en: 'Cash Dividend' }, rightDetails: { ko: '배당금 지급', en: 'Dividend Payment' }, rightQty: 180, baseRate: 1, amount: 129600, taxes: 19958 },
  ],
  riskExposure: {
    ko: '해당 계좌는 국내주식 및 채권 중심으로 운용되며, 시장 변동성에 따라 평가금액이 변동될 수 있습니다.',
    en: 'This account is managed primarily in domestic equities and bonds, and the valuation amount may fluctuate with market volatility.',
  },
  advisoryFirm: { ko: '해당 사항 없음', en: 'Not applicable' },
  feeHistory: [
    { from: '2024.03.18', to: '2024.06.18', discretionaryFee: 137150, performanceFee: 0, otherTradeCost: 0, taxes: 13715, otherCost: 0, totalCost: 150865 },
  ],
  wrapFeeBasis: {
    ko: '랩수수료는 계약금액을 기준으로 연 0.8%를 분기별로 나누어 후취 방식으로 부과합니다.',
    en: 'The wrap fee is charged quarterly in arrears at an annual rate of 0.8% based on the contract amount.',
  },
  performanceFeeBasis: {
    ko: '별도의 성과보수는 부과하지 않습니다.',
    en: 'No separate performance fee is charged.',
  },
  personnel: [
    {
      position: { ko: '팀장', en: 'Team Lead' },
      name: { ko: '카리나', en: 'Karina' },
      startDate: '2020.07.01',
      contractCount: 97,
      scale: 38600,
      career: { ko: '신한자산운용 주식운용팀 8년 경력', en: '8 years at Shinhan Asset Management Equity Management Team' },
      contact: { ko: '02-1588-0365', en: '+82-2-1588-0365' },
    },
  ],
  additionalNote: null,
  recommenderInfo: { ko: '신한투자증권 강남금융센터', en: 'Shinhan Investment Corp. Gangnam Finance Center' },
  recommenderContact: { ko: '02-1588-0365', en: '+82-2-1588-0365' },
  signDate: '2024년06월18일',
};
