// 실제 고객 데이터가 아닌, 화면 구조를 보여주기 위한 예시(더미) 데이터입니다.
// 랩 성과보고서 기본형과 문구가 거의 동일하여 공통 문구는 그대로 재사용합니다.
import { text as baseText } from './wrapReportDomesticBasicData';

export const text = {
  ...baseText,
  assetTypeWeightTit: { ko: '자산 유형별 비중', en: 'Weight by Asset Type' },
  s3bTit: { ko: '나. 자산 종류별 현황', en: 'b. Status by Asset Category' },
  securityWeightTit: { ko: '유가 증권별 비중', en: 'Weight by Security' },
  countryWeightTit: { ko: '국가별 자산 비중', en: 'Weight by Country' },
  s3cTit: { ko: '다. 자산 종목 보유 현황', en: 'c. Asset Holdings Status' },
};

export const sampleData = {
  baseDate: '2024-06-18',
  contractor: { ko: '류원희', en: 'Wonhee Ryu' },
  productName: { ko: '신한 마이더스 글로벌 자산배분 랩', en: 'Shinhan Midas Global Asset Allocation Wrap' },
  accountNo: '50293841762',
  firstContractDate: '2021.11.15',
  investPeriod: 946,
  infoBaseDate: '2024.06.18',
  principal: 60000000,
  withdrawal: 3000000,
  fees: 452800,
  valuation: 68215400,
  cumulativeReturn: 15.36,
  annualizedReturn: 5.98,
  terminationDeduction: 150000,
  expectedTermination: 68065400,
  contractAmount: 60000000,
  reportValuation: 68215400,
  cumulativeProfit: 8215400,
  cumulativeReturnFrom: '21년11월15일',
  cumulativeReturnTo: '24년06월18일',
  cumulativeReturnPct: 15.36,
  quarterlyProfit: 745200,
  quarterlyReturnFrom: '24년03월18일',
  quarterlyReturnTo: '24년06월18일',
  quarterlyReturnPct: 1.11,
  wrapService: { ko: '신한 마이더스 글로벌 자산배분 랩', en: 'Shinhan Midas Global Asset Allocation Wrap' },
  accountName: { ko: '류원희', en: 'Wonhee Ryu' },
  riskTendency: { ko: '적극투자형', en: 'Aggressive' },
  riskGrade: { ko: '2등급', en: 'Grade 2' },
  serviceRegDate: '2021.11.15',
  contractFrom: '2021.11.15',
  contractTo: '2026.11.15',
  overseasInvest: { ko: '해당', en: 'Yes' },
  benchmark: { ko: 'MSCI ACWI', en: 'MSCI ACWI' },
  expectedMaturity: '2026.11.15',
  wrapBranch: { ko: '판교금융센터', en: 'Pangyo Finance Center' },
  wrapManager: { ko: '한지민', en: 'Jimin Han' },
  managingFirm: { ko: '신한자산운용', en: 'Shinhan Asset Management' },
  managingAgent: { ko: '유재석', en: 'Jaeseok Yoo' },
  investTendency: { ko: '적극투자형', en: 'Aggressive' },
  restriction: { ko: '해당없음', en: 'None' },
  periodReturns: [
    { division: { ko: '수익률(%)', en: 'Return (%)' }, m3: 1.86, m6: 4.20, m9: 8.55, m12: 12.10, cumulative: 15.36 },
  ],
  cumulativeLine: [
    { date: '23.06', value: 5.0 }, { date: '23.09', value: 7.8 }, { date: '23.12', value: 10.6 },
    { date: '24.03', value: 13.9 }, { date: '24.06', value: 15.36 },
  ],
  recent3mLine: [
    { date: '04.01', value: 0.3 }, { date: '04.15', value: 0.6 }, { date: '05.01', value: 0.4 },
    { date: '05.15', value: 0.8 }, { date: '06.01', value: 1.0 }, { date: '06.18', value: 1.11 },
  ],
  returnComposition: [
    { assetClass: { ko: '해외주식', en: 'Overseas Equity' }, priorReturn: 1.6, currentReturn: 1.9, cumulativeReturn: 11.4, holding: { ko: '보유중', en: 'Held' }, currentWeight: 50, priorWeight: 45 },
    { assetClass: { ko: '해외채권', en: 'Overseas Bond' }, priorReturn: 0.7, currentReturn: 0.8, cumulativeReturn: 4.2, holding: { ko: '보유중', en: 'Held' }, currentWeight: 30, priorWeight: 35 },
    { assetClass: { ko: '외화유동성', en: 'FX Liquidity' }, priorReturn: 0.1, currentReturn: 0.1, cumulativeReturn: 0.5, holding: { ko: '보유중', en: 'Held' }, currentWeight: 20, priorWeight: 20 },
  ],
  assetTypeHeaderCurrent: { ko: '당분기말', en: 'Current Quarter' },
  assetTypeHeaderPrior: { ko: '전분기말', en: 'Prior Quarter' },
  assetTypeRows: [
    { name: { ko: '해외주식', en: 'Overseas Equity' }, currentAmount: 34107700, currentWeight: 50.0, priorAmount: 28500000, priorWeight: 45.0 },
    { name: { ko: '해외채권', en: 'Overseas Bond' }, currentAmount: 20464620, currentWeight: 30.0, priorAmount: 22200000, priorWeight: 35.0 },
    { name: { ko: '외화유동성', en: 'FX Liquidity' }, currentAmount: 13643080, currentWeight: 20.0, priorAmount: 12666700, priorWeight: 20.0 },
  ],
  assetTypeSum: { name: { ko: '합계', en: 'Total' }, currentAmount: 68215400, currentWeight: 100.0, priorAmount: 63366700, priorWeight: 100.0 },
  securityHeaderCurrent: { ko: '당분기말', en: 'Current Quarter' },
  securityHeaderPrior: { ko: '전분기말', en: 'Prior Quarter' },
  securityRows: [
    { name: { ko: '미국주식ETF', en: 'US Equity ETF' }, currentAmount: 27286160, currentWeight: 40.0, priorAmount: 22178300, priorWeight: 35.0 },
    { name: { ko: '미국채권ETF', en: 'US Bond ETF' }, currentAmount: 20464620, currentWeight: 30.0, priorAmount: 22200000, priorWeight: 35.0 },
    { name: { ko: '신흥국주식ETF', en: 'EM Equity ETF' }, currentAmount: 6821540, currentWeight: 10.0, priorAmount: 6336700, priorWeight: 10.0 },
    { name: { ko: 'MMF(외화)', en: 'FX MMF' }, currentAmount: 13643080, currentWeight: 20.0, priorAmount: 12651700, priorWeight: 20.0 },
  ],
  countryRows: [
    { name: { ko: '미국', en: 'United States' }, weight: 68.0 },
    { name: { ko: '신흥국', en: 'Emerging Markets' }, weight: 18.0 },
    { name: { ko: '유럽', en: 'Europe' }, weight: 9.0 },
    { name: { ko: '기타', en: 'Other' }, weight: 5.0 },
  ],
  holdings: [
    { division: { ko: 'ETF', en: 'ETF' }, name: { ko: 'Vanguard S&P 500 ETF', en: 'Vanguard S&P 500 ETF' }, currency: { ko: 'USD', en: 'USD' }, region: { ko: '미국', en: 'US' }, qty: 42, avgPrice: 468.2, currentPrice: 512.6, returnRate: 9.48 },
    { division: { ko: 'ETF', en: 'ETF' }, name: { ko: 'iShares Core US Aggregate Bond ETF', en: 'iShares Core US Aggregate Bond ETF' }, currency: { ko: 'USD', en: 'USD' }, region: { ko: '미국', en: 'US' }, qty: 210, avgPrice: 98.1, currentPrice: 99.4, returnRate: 1.33 },
  ],
  managementStatus: {
    ko: '분기 중 신흥국 주식 비중을 소폭 확대하고, 달러 강세에 대응해 외화유동성을 일부 확보했습니다.',
    en: 'This quarter, we slightly increased emerging market equity weighting and secured some FX liquidity in response to dollar strength.',
  },
  managementPlan: {
    ko: '다음 분기에는 글로벌 금리 인하 국면에 대비해 채권 비중을 확대할 계획입니다.',
    en: 'Next quarter, we plan to increase bond allocation in preparation for a global rate-cutting cycle.',
  },
  trades: [
    { division: { ko: '매수', en: 'Buy' }, name: { ko: 'Vanguard S&P 500 ETF', en: 'Vanguard S&P 500 ETF' }, date: '2024-05-08', qty: 5, price: 505.2, amount: 2526, fee: 4, tax: 0 },
  ],
  mmw: [
    { from: '2024.03.18', to: '2024.06.18', totalInvested: 341000000, totalRedeemed: 340200000, profitLoss: 57800 },
  ],
  buyAmount: 22800000,
  sellAmount: 21400000,
  turnoverCurrent: 9.4,
  turnoverCurrentFrom: '2024.03.18',
  turnoverCurrentTo: '2024.06.18',
  turnoverCumulative: 42.1,
  turnoverCumulativeFrom: '2021.11.15',
  turnoverCumulativeTo: '2024.06.18',
  deposits: [
    { month: '2024.06', deposit: 0, withdrawal: 0, balance: 0 },
  ],
  rights: [
    { division: { ko: '분배금', en: 'Distribution' }, name: { ko: 'Vanguard S&P 500 ETF', en: 'Vanguard S&P 500 ETF' }, detailDivision: { ko: '현금분배', en: 'Cash Distribution' }, rightDetails: { ko: '분배금 지급', en: 'Distribution Payment' }, rightQty: 42, baseRate: 1385.2, amount: 52000, taxes: 8008 },
  ],
  riskExposure: {
    ko: '해당 계좌는 해외주식 및 채권 중심으로 운용되며, 환율 및 해외시장 변동성에 따라 평가금액이 변동될 수 있습니다.',
    en: 'This account is managed primarily in overseas equities and bonds, and the valuation amount may fluctuate with exchange rates and overseas market volatility.',
  },
  advisoryFirm: { ko: '해당 사항 없음', en: 'Not applicable' },
  feeHistory: [
    { from: '2024.03.18', to: '2024.06.18', discretionaryFee: 170500, performanceFee: 0, otherTradeCost: 0, taxes: 17050, otherCost: 0, totalCost: 187550 },
  ],
  wrapFeeBasis: {
    ko: '랩수수료는 계약금액을 기준으로 연 1.0%를 분기별로 나누어 후취 방식으로 부과합니다.',
    en: 'The wrap fee is charged quarterly in arrears at an annual rate of 1.0% based on the contract amount.',
  },
  performanceFeeBasis: {
    ko: '별도의 성과보수는 부과하지 않습니다.',
    en: 'No separate performance fee is charged.',
  },
  personnel: [
    {
      position: { ko: '팀장', en: 'Team Lead' },
      name: { ko: '유재석', en: 'Jaeseok Yoo' },
      startDate: '2017.05.01',
      contractCount: 168,
      scale: 74300,
      career: { ko: '신한자산운용 글로벌자산배분팀 14년 경력', en: '14 years at Shinhan Asset Management Global Asset Allocation Team' },
      contact: { ko: '02-1588-0365', en: '+82-2-1588-0365' },
    },
  ],
  recommenderInfo: { ko: '신한투자증권 판교금융센터', en: 'Shinhan Investment Corp. Pangyo Finance Center' },
  recommenderContact: { ko: '02-1588-0365', en: '+82-2-1588-0365' },
  signDate: '2024년06월18일',
};
